#!/bin/bash
# ARIA Quick Setup Script
# Run this to integrate ARIA into WorldMonitor

echo "🤖 ARIA Integration Setup"
echo "=========================="
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Register ARIA Panel${NC}"
echo "------"
echo "Edit src/config/panels.ts and add:"
echo ""
echo "  import { AriaPanel } from '../components/AriaPanel';"
echo ""
echo "  const PANELS = ["
echo "    // ... existing panels"
echo "    {"
echo "      name: 'aria',"
echo "      label: 'ARIA Intelligence',"
echo "      component: AriaPanel,"
echo "      defaultWidth: 4,"
echo "      defaultHeight: 5,"
echo "      premium: false,"
echo "    },"
echo "  ];"
echo ""
read -p "Press Enter when done..."
echo ""

echo -e "${BLUE}Step 2: Add to Variant${NC}"
echo "------"
echo "Edit src/config/variants/full.ts and add 'aria' to defaultPanels:"
echo ""
echo "  export const fullVariant = {"
echo "    defaultPanels: ["
echo "      // ... existing panels"
echo "      'aria',"
echo "    ],"
echo "  };"
echo ""
read -p "Press Enter when done..."
echo ""

echo -e "${BLUE}Step 3: Wire Data Loading${NC}"
echo "------"
echo "Edit src/app/data-loader.ts and add:"
echo ""
echo "  import { getCachedAwarenessState } from '../services/aria';"
echo ""
echo "  async function loadAppData(ctx) {"
echo "    const ariaAwareness = await getCachedAwarenessState()"
echo "      .catch(() => null);"
echo "    ctx.ariaAwareness = ariaAwareness;"
echo "  }"
echo ""
read -p "Press Enter when done..."
echo ""

echo -e "${BLUE}Step 4: Update App Context${NC}"
echo "------"
echo "Edit src/app/app-context.ts and add:"
echo ""
echo "  interface AppContext {"
echo "    // ... existing properties"
echo "    ariaAwareness?: AwarenessState;"
echo "    enableAria?: boolean;"
echo "  }"
echo ""
read -p "Press Enter when done..."
echo ""

echo -e "${BLUE}Step 5: Configure Environment${NC}"
echo "------"
echo "Add to .env.local or .env:"
echo ""
echo "  VITE_ENABLE_ARIA=true"
echo "  VITE_LLM_API_KEY=your_api_key_here"
echo ""
read -p "Press Enter when done..."
echo ""

echo -e "${BLUE}Step 6: Start Development Server${NC}"
echo "------"
echo "Running: npm run dev"
echo ""
npm run dev &
sleep 3

echo ""
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo ""
echo "ARIA is now integrated into WorldMonitor!"
echo ""
echo "Next steps:"
echo "1. Open http://localhost:5173 in your browser"
echo "2. Add ARIA panel to the dashboard"
echo "3. Click on ARIA and ask a question"
echo "4. Watch ARIA stream back an intelligent response"
echo ""
echo "Example questions to ask ARIA:"
echo "  - 'What are the current global risks?'"
echo "  - 'Analyze recent market movements'"
echo "  - 'What is happening in active conflicts?'"
echo "  - 'Summarize the latest news'"
echo ""
echo -e "${YELLOW}For detailed documentation, see:${NC}"
echo "  - ARIA_README.md - Complete user guide"
echo "  - ARIA_INTEGRATION.md - Developer integration guide"
echo "  - ARIA_SETUP.ts - Configuration examples"
echo ""
