import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// English is always needed as fallback. The full dictionary is split:
// `en.shell.json` covers the critical-path UI (header, panel chrome,
// command palette, common toasts) and is statically imported so it ships
// in the i18n chunk. `en.rest.json` covers per-panel content and is
// dynamically imported during init() — Vite emits it as a separate
// `i18n-en-rest` chunk so it's parsed off the critical path. Both are
// awaited before init resolves, so every t() call sees the full merged
// dictionary by the time any panel renders.
//
// Important offline note: because init blocks on the rest chunk, that
// chunk MUST be in the SW precache (alongside the app shell) — otherwise
// an offline-after-install boot would hang. The vite.config.ts
// manualChunks routing names it `i18n-en-rest` rather than
// `locale-en-rest` precisely so it falls outside the SW's
// `globIgnores: '**/locale-*.js'` rule and gets precached.
//
// Source of truth stays at en.json; the two derived files are
// regenerated by scripts/build-i18n-shell.mjs (wired into prebuild) and
// a parity test blocks drift.
import enShell from '../locales/en.shell.json';

const SUPPORTED_LANGUAGES = ['en', 'bg', 'cs', 'fr', 'de', 'el', 'es', 'it', 'pl', 'pt', 'nl', 'sv', 'ru', 'ar', 'zh', 'ja', 'ko', 'ro', 'tr', 'th', 'vi'] as const;
type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number];
type TranslationDictionary = Record<string, unknown>;

const SUPPORTED_LANGUAGE_SET = new Set<SupportedLanguage>(SUPPORTED_LANGUAGES);
const loadedLanguages = new Set<SupportedLanguage>();

// Lazy-load only the locale that's actually needed — all others stay out of the bundle.
const localeModules = import.meta.glob<TranslationDictionary>(
  ['../locales/*.json', '!../locales/en.json', '!../locales/en.shell.json', '!../locales/en.rest.json'],
  { import: 'default' },
);

// Cached to keep init+changeLanguage idempotent — Vite returns the same
// module instance on repeat dynamic imports, but caching the merged dict
// avoids re-spreading a 100-key object on every ensureLanguageLoaded('en').
let enFullPromise: Promise<TranslationDictionary> | null = null;
function loadEnFull(): Promise<TranslationDictionary> {
  if (enFullPromise) return enFullPromise;
  enFullPromise = import('../locales/en.rest.json').then((mod) => {
    const rest = (mod.default ?? mod) as TranslationDictionary;
    const shellDict = enShell as TranslationDictionary;
    // Shallow spread is insufficient: `components` is a top-level key in
    // BOTH shell (panel/deckgl/map) and rest (everything else), so a plain
    // `{ ...shell, ...rest }` would clobber shell.components and silently
    // drop panel/deckgl/map. Production was previously rescued by i18next
    // deep-merging the shell-then-rest sequence at init, but the cached
    // value here MUST itself be the full dict so direct readers and any
    // future fresh-i18next paths stay correct.
    const merged: TranslationDictionary = { ...shellDict, ...rest };
    if (shellDict.components && rest.components) {
      merged.components = {
        ...(shellDict.components as Record<string, unknown>),
        ...(rest.components as Record<string, unknown>),
      };
    }
    return merged;
  });
  return enFullPromise;
}

const RTL_LANGUAGES = new Set(['ar']);

function normalizeLanguage(lng: string): SupportedLanguage {
  const base = (lng || 'en').split('-')[0]?.toLowerCase() || 'en';
  if (SUPPORTED_LANGUAGE_SET.has(base as SupportedLanguage)) {
    return base as SupportedLanguage;
  }
  return 'en';
}

function applyDocumentDirection(lang: string): void {
  const base = lang.split('-')[0] || lang;
  document.documentElement.setAttribute('lang', base === 'zh' ? 'zh-CN' : base);
  if (RTL_LANGUAGES.has(base)) {
    document.documentElement.setAttribute('dir', 'rtl');
  } else {
    document.documentElement.removeAttribute('dir');
  }
}

async function ensureLanguageLoaded(lng: string): Promise<SupportedLanguage> {
  const normalized = normalizeLanguage(lng);
  if (loadedLanguages.has(normalized) && i18next.hasResourceBundle(normalized, 'translation')) {
    return normalized;
  }

  let translation: TranslationDictionary;
  if (normalized === 'en') {
    translation = await loadEnFull();
  } else {
    const loader = localeModules[`../locales/${normalized}.json`];
    if (!loader) {
      console.warn(`No locale file for "${normalized}", falling back to English`);
      translation = await loadEnFull();
    } else {
      translation = await loader();
    }
  }

  i18next.addResourceBundle(normalized, 'translation', translation, true, true);
  loadedLanguages.add(normalized);
  return normalized;
}

// Initialize i18n
export async function initI18n(): Promise<void> {
  if (i18next.isInitialized) {
    const currentLanguage = normalizeLanguage(i18next.language || 'en');
    await ensureLanguageLoaded(currentLanguage);
    applyDocumentDirection(i18next.language || currentLanguage);
    return;
  }

  // Boot i18next with the eagerly-imported shell so the critical-path
  // chrome (header, common toasts, panel buttons) renders before the
  // larger `en.rest` chunk has finished loading. The full English bundle
  // — and any detected non-English locale — gets merged in below.
  await i18next
    .use(LanguageDetector)
    .init({
      resources: {
        en: { translation: enShell as TranslationDictionary },
      },
      supportedLngs: [...SUPPORTED_LANGUAGES],
      nonExplicitSupportedLngs: true,
      fallbackLng: 'en',
      debug: import.meta.env.DEV,
      interpolation: {
        escapeValue: false, // not needed for these simple strings
      },
      detection: {
        order: ['localStorage', 'navigator'],
        caches: ['localStorage'],
      },
    });

  // Always finish loading the English rest-chunk — it's the fallback for
  // every t() call regardless of the detected locale, so panel content
  // keys like `components.economic.title` must resolve even when the
  // user's language is Arabic and that locale's bundle is still loading.
  const fullEn = await loadEnFull();
  i18next.addResourceBundle('en', 'translation', fullEn, true, true);
  loadedLanguages.add('en');

  const detectedLanguage = await ensureLanguageLoaded(i18next.language || 'en');
  if (detectedLanguage !== 'en') {
    // Re-trigger translation resolution now that the detected bundle is loaded.
    await i18next.changeLanguage(detectedLanguage);
  }

  applyDocumentDirection(i18next.language || detectedLanguage);
}

// Helper to translate
export function t(key: string, options?: Record<string, unknown>): string {
  return i18next.t(key, options);
}

// Helper to change language
export async function changeLanguage(lng: string): Promise<void> {
  const normalized = await ensureLanguageLoaded(lng);
  await i18next.changeLanguage(normalized);
  applyDocumentDirection(normalized);
  window.location.reload(); // Simple reload to update all components for now
}

// Helper to get current language (normalized to short code)
export function getCurrentLanguage(): string {
  const lang = i18next.language || 'en';
  return lang.split('-')[0]!;
}

export function isRTL(): boolean {
  return RTL_LANGUAGES.has(getCurrentLanguage());
}

export function getLocale(): string {
  const lang = getCurrentLanguage();
  const map: Record<string, string> = { en: 'en-US', bg: 'bg-BG', cs: 'cs-CZ', el: 'el-GR', zh: 'zh-CN', pt: 'pt-BR', ja: 'ja-JP', ko: 'ko-KR', ro: 'ro-RO', tr: 'tr-TR', th: 'th-TH', vi: 'vi-VN' };
  return map[lang] || lang;
}

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'bg', label: 'Български', flag: '🇧🇬' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
  { code: 'cs', label: 'Čeština', flag: '🇨🇿' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'el', label: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'it', label: 'Italiano', flag: '🇮🇹' },
  { code: 'pl', label: 'Polski', flag: '🇵🇱' },
  { code: 'pt', label: 'Português', flag: '🇵🇹' },
  { code: 'nl', label: 'Nederlands', flag: '🇳🇱' },
  { code: 'sv', label: 'Svenska', flag: '🇸🇪' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
  { code: 'ro', label: 'Română', flag: '🇷🇴' },
  { code: 'th', label: 'ไทย', flag: '🇹🇭' },
  { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
  { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
];
