import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const portfolioImpactSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/PortfolioImpactPanel.ts', 'utf8');
const ideaRadarSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/IdeaRadarPanel.ts', 'utf8');
const insightsSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/InsightsPanel.ts', 'utf8');
const economicSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/EconomicPanel.ts', 'utf8');
const supplyChainSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/SupplyChainPanel.ts', 'utf8');
const etfFlowsSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/ETFFlowsPanel.ts', 'utf8');
const gulfEconomiesSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/GulfEconomiesPanel.ts', 'utf8');
const economicCalendarSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/EconomicCalendarPanel.ts', 'utf8');
const cotPositioningSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/CotPositioningPanel.ts', 'utf8');
const goldIntelligenceSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/GoldIntelligencePanel.ts', 'utf8');
const liquidityShiftsSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/LiquidityShiftsPanel.ts', 'utf8');
const marketBreadthSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/MarketBreadthPanel.ts', 'utf8');
const yieldCurveSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/YieldCurvePanel.ts', 'utf8');
const stablecoinSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/StablecoinPanel.ts', 'utf8');
const fearGreedSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/FearGreedPanel.ts', 'utf8');
const macroTilesSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/MacroTilesPanel.ts', 'utf8');
const fsiSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/FSIPanel.ts', 'utf8');
const aaiiSentimentSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/AAIISentimentPanel.ts', 'utf8');
const groceryBasketSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/GroceryBasketPanel.ts', 'utf8');
const fuelPricesSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/FuelPricesPanel.ts', 'utf8');
const bigMacSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/BigMacPanel.ts', 'utf8');
const faoFoodPriceIndexSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/FaoFoodPriceIndexPanel.ts', 'utf8');
const consumerPricesSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/ConsumerPricesPanel.ts', 'utf8');
const tradePolicySource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/TradePolicyPanel.ts', 'utf8');
const sanctionsPressureSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/SanctionsPressurePanel.ts', 'utf8');
const securityAdvisoriesSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/SecurityAdvisoriesPanel.ts', 'utf8');
const climateAnomalySource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/ClimateAnomalyPanel.ts', 'utf8');
const populationExposureSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/PopulationExposurePanel.ts', 'utf8');
const pipelineStatusSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/PipelineStatusPanel.ts', 'utf8');
const storageFacilityMapSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/StorageFacilityMapPanel.ts', 'utf8');
const fuelShortageSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/FuelShortagePanel.ts', 'utf8');
const energyDisruptionsSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/EnergyDisruptionsPanel.ts', 'utf8');
const economicCalendarTitleSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/EconomicCalendarPanel.ts', 'utf8');
const renewableSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/RenewableEnergyPanel.ts', 'utf8');
const cotTitleSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/CotPositioningPanel.ts', 'utf8');
const aaiiTitleSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/AAIISentimentPanel.ts', 'utf8');
const socialVelocityTitleSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/SocialVelocityPanel.ts', 'utf8');
const energyRiskOverviewSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/EnergyRiskOverviewPanel.ts', 'utf8');
const energyCrisisSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/EnergyCrisisPanel.ts', 'utf8');
const forecastSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/ForecastPanel.ts', 'utf8');
const ucdpEventsSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/UcdpEventsPanel.ts', 'utf8');
const diseaseOutbreaksSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/DiseaseOutbreaksPanel.ts', 'utf8');
const socialVelocitySource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/SocialVelocityPanel.ts', 'utf8');
const dataLoaderSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/app/data-loader.ts', 'utf8');
const panelSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/Panel.ts', 'utf8');
const marketPanelSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/MarketPanel.ts', 'utf8');
const worldClockSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/WorldClockPanel.ts', 'utf8');
const watchlistModalSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/watchlist-modal.ts', 'utf8');
const breakthroughsSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/BreakthroughsTickerPanel.ts', 'utf8');
const speciesSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/components/SpeciesComebackPanel.ts', 'utf8');
const panelLayoutSource = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/app/panel-layout.ts', 'utf8');
const jaLocale = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/locales/ja.json', 'utf8');
const enLocale = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/locales/en.json', 'utf8');
const panelsCss = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/styles/panels.css', 'utf8');
const mainCss = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/src/styles/main.css', 'utf8');
const indexHtml = fs.readFileSync('/Users/lab2/AI/AI_1/worldmonitor/index.html', 'utf8');

test('portfolio impact renders a quick-read brief at the top', () => {
  assert.match(portfolioImpactSource, /this\.buildQuickRead\(this\.viewModel\)/);
  assert.match(portfolioImpactSource, /\?\s*'クイック確認'\s*:\s*'Quick Read'/);
  assert.match(portfolioImpactSource, /'portfolio-impact-section finance-guide-brief'/);
  assert.match(portfolioImpactSource, /private static readonly ACTION_LIMIT = 3/);
  assert.match(portfolioImpactSource, /private static readonly MOBILE_ACTION_LIMIT = 2/);
  assert.match(portfolioImpactSource, /private static readonly HOLDING_LIMIT = 4/);
  assert.match(portfolioImpactSource, /private static readonly MOBILE_HOLDING_LIMIT = 3/);
  assert.match(portfolioImpactSource, /actions\.length\}件中 \$\{limit\}件を表示/);
  assert.match(portfolioImpactSource, /portfolio-impact-section portfolio-impact-holdings/);
  assert.match(portfolioImpactSource, /private static readonly THEME_LIMIT = 3/);
  assert.match(portfolioImpactSource, /private static readonly RULE_LIMIT = 3/);
});

test('idea radar renders a session-focus brief at the top', () => {
  assert.match(ideaRadarSource, /this\.renderSessionFocusSection\(this\.viewModel, this\.evaluationSummary\)/);
  assert.match(ideaRadarSource, /\?\s*'注目ポイント'\s*:\s*'Session Focus'/);
  assert.match(ideaRadarSource, /\$\{ja \? '市場環境' : 'Regime'\} \$\{this\.translateIdeaText\(headline\)\}/);
  assert.match(ideaRadarSource, /\$\{ja \? '補正' : 'Calibration'\} \$\{this\.translateIdeaText\(calibration\)\}/);
  assert.match(ideaRadarSource, /private static readonly HORIZON_CANDIDATE_LIMIT = 3/);
  assert.match(ideaRadarSource, /private static readonly MOBILE_PLAYBOOK_LIMIT = 1/);
  assert.match(ideaRadarSource, /private static readonly MOBILE_BEGINNER_SUMMARY_LIMIT = 1/);
  assert.match(ideaRadarSource, /private static readonly PLAYBOOK_STORAGE_KEY = 'idea-radar-playbook-expanded'/);
  assert.match(ideaRadarSource, /private playbookExpanded = this\.loadPlaybookExpanded\(\);/);
  assert.match(ideaRadarSource, /portfolio-impact-section idea-radar-beginner-summary/);
  assert.match(ideaRadarSource, /candidates\.length\}件中 \$\{IdeaRadarPanel\.HORIZON_CANDIDATE_LIMIT\}件を表示/);
  assert.match(ideaRadarSource, /portfolio-impact-section idea-radar-playbook/);
  assert.match(ideaRadarSource, /idea-radar-playbook-toggle/);
  assert.match(ideaRadarSource, /localStorage\?\.setItem\(IdeaRadarPanel\.PLAYBOOK_STORAGE_KEY, String\(expanded\)\)/);
});

test('guide panels fail open instead of sticking on retry spinners', () => {
  assert.match(ideaRadarSource, /localizedMessage = this\.isJapanese\(\) && message === 'Idea radar is temporarily unavailable\. Core finance panels continue loading\.'/);
  assert.doesNotMatch(ideaRadarSource, /this\.showError\(this\.error/);
  assert.match(portfolioImpactSource, /buildUnavailableViewModel\(\)/);
  assert.doesNotMatch(portfolioImpactSource, /this\.showError\(this\.error/);
});

test('optional finance analytics fail open with compact unavailable states', () => {
  assert.match(panelSource, /protected renderExternalUnavailableState\(options: \{/);
  assert.match(panelSource, /const normalizeText = \(value: unknown\): string => \{/);
  assert.match(panelSource, /'textContent' in value/);
  assert.match(panelSource, /\$\{escapeHtml\(sourceLabel\)\}: \$\{escapeHtml\(source\)\}/);
  assert.match(insightsSource, /renderUnavailableState\('AI market insights are temporarily unavailable\. Core finance panels continue loading\.'/);
  assert.doesNotMatch(insightsSource, /this\.showError\(\);/);
  assert.match(insightsSource, /source: 'AI inference and market context feeds'/);
  assert.match(economicSource, /private renderExternalEmptyMarkup\(message: string, source: string, detail\?: string\): string/);
  assert.match(economicSource, /const sourceLabel = document\?\.documentElement\?\.lang === 'ja' \? 'ソース' : 'Source'/);
  assert.match(economicSource, /this\.renderExternalEmptyMarkup\([\s\S]*?'External stress index data is temporarily unavailable\.', 'FRED'\)/);
  assert.match(supplyChainSource, /private renderUnavailableState\(message: string\): string/);
  assert.match(supplyChainSource, /ソース: チョークポイント・海運・ストレス・鉱物フィード/);
  assert.match(supplyChainSource, /this\.chokepointData\?\.upstreamUnavailable/);
  assert.match(supplyChainSource, /this\.shippingData\?\.upstreamUnavailable/);
  assert.match(supplyChainSource, /this\.stressData\?\.upstreamUnavailable/);
  assert.match(supplyChainSource, /this\.mineralsData\?\.upstreamUnavailable/);
  assert.match(etfFlowsSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(etfFlowsSource, /source: 'ETF flow and market quote feeds'/);
  assert.doesNotMatch(etfFlowsSource, /this\.showError\(this\.error/);
  assert.match(gulfEconomiesSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(gulfEconomiesSource, /source: 'Gulf exchange and FX market feeds'/);
  assert.doesNotMatch(gulfEconomiesSource, /this\.showError\(t\('common\.failedMarketData'\)/);
  assert.match(economicCalendarSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(economicCalendarSource, /source: 'Economic calendar aggregator'/);
  assert.doesNotMatch(economicCalendarSource, /this\.showError\('Economic calendar data unavailable\.'/);
  assert.match(cotPositioningSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(cotPositioningSource, /source: 'CFTC Commitments of Traders'/);
  assert.doesNotMatch(cotPositioningSource, /this\.showError\('COT data unavailable'/);
  assert.match(goldIntelligenceSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(goldIntelligenceSource, /source: 'Gold price, ETF flow, and central bank reserve feeds'/);
  assert.doesNotMatch(goldIntelligenceSource, /this\.showError\('Gold data unavailable'/);
  assert.match(liquidityShiftsSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(liquidityShiftsSource, /source: 'Central bank and market liquidity feeds'/);
  assert.doesNotMatch(liquidityShiftsSource, /this\.showError\(t\('components\.liquidityShifts\.unavailable'\)/);
  assert.match(marketBreadthSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(marketBreadthSource, /source: 'Market breadth and exchange statistics feeds'/);
  assert.doesNotMatch(marketBreadthSource, /this\.showError\(t\('common\.noDataShort'\)/);
  assert.match(yieldCurveSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(yieldCurveSource, /source: 'FRED \/ ECB'/);
  assert.doesNotMatch(yieldCurveSource, /this\.showError\('No yield data available'/);
  assert.match(stablecoinSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(stablecoinSource, /source: 'Stablecoin market and on-chain liquidity feeds'/);
  assert.doesNotMatch(stablecoinSource, /this\.showError\(this\.error \|\| t\('common\.noDataShort'\)/);
  assert.match(fearGreedSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(fearGreedSource, /source: 'CNN \/ AAII \/ volatility and credit feeds'/);
  assert.doesNotMatch(fearGreedSource, /this\.showError\(/);
  assert.match(macroTilesSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(macroTilesSource, /source: 'FRED \/ Eurostat \/ ECB'/);
  assert.doesNotMatch(macroTilesSource, /this\.showError\(/);
  assert.match(fsiSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(fsiSource, /source: 'FRED \/ ECB'/);
  assert.doesNotMatch(fsiSource, /this\.showError\(/);
  assert.match(aaiiSentimentSource, /private renderUnavailableState\(message: string\): void/);
  assert.match(aaiiSentimentSource, /source: 'AAII weekly sentiment survey'/);
  assert.doesNotMatch(aaiiSentimentSource, /this\.showError\(/);
  assert.match(groceryBasketSource, /private renderUnavailableState\(message: string\): void/);
  assert.doesNotMatch(groceryBasketSource, /this\.showError\(/);
  assert.match(fuelPricesSource, /private renderUnavailableState\(message: string\): void/);
  assert.doesNotMatch(fuelPricesSource, /this\.showError\(/);
  assert.match(bigMacSource, /private renderUnavailableState\(message: string\): void/);
  assert.doesNotMatch(bigMacSource, /this\.showError\(/);
  assert.match(faoFoodPriceIndexSource, /private renderUnavailableState\(message: string\): void/);
  assert.doesNotMatch(faoFoodPriceIndexSource, /this\.showError\(/);
  assert.match(consumerPricesSource, /消費者価格スナップショットは現在利用できません/);
  assert.match(consumerPricesSource, /カテゴリ別価格データは現在利用できません/);
  assert.match(consumerPricesSource, /価格変動データは現在利用できません/);
  assert.match(consumerPricesSource, /小売比較データは現在利用できません/);
  assert.match(consumerPricesSource, /小売更新データは現在利用できません/);
  assert.match(tradePolicySource, /private renderExternalEmptyMarkup\(message: string, source: string, detail\?: string\): string/);
  assert.match(tradePolicySource, /External trade restriction data is temporarily unavailable\./);
  assert.match(tradePolicySource, /External customs revenue data is temporarily unavailable\./);
  assert.match(tradePolicySource, /External strategic trade flow data is temporarily unavailable\./);
  assert.match(tradePolicySource, /Source: \$\{escapeHtml\(source\)\}/);
  assert.match(sanctionsPressureSource, /this\.renderExternalUnavailableState\(\{/);
  assert.match(sanctionsPressureSource, /External sanctions designation data is temporarily unavailable\./);
  assert.match(sanctionsPressureSource, /source: 'OFAC sanctions feed'/);
  assert.match(sanctionsPressureSource, /No country-level sanctions pressure rows are currently available\./);
  assert.match(securityAdvisoriesSource, /現在、注視すべき渡航・保健アドバイザリーはありません。/);
  assert.match(securityAdvisoriesSource, /ソース: 渡航勧告・公衆衛生ブリテン/);
  assert.match(climateAnomalySource, /ソース: 気候異常・気象影響フィード/);
  assert.match(populationExposureSource, /現在、監視閾値を超える人口露出イベントはありません。/);
  assert.match(populationExposureSource, /ソース: 紛争・気候・災害の露出レイヤー/);
  assert.match(pipelineStatusSource, /Pipeline registry is temporarily unavailable\./);
  assert.match(pipelineStatusSource, /source: 'Pipeline registry and operator evidence feeds'/);
  assert.doesNotMatch(pipelineStatusSource, /this\.showError\('Pipeline registry unavailable'/);
  assert.match(storageFacilityMapSource, /Storage registry is temporarily unavailable\./);
  assert.match(storageFacilityMapSource, /source: 'Storage registry and operator evidence feeds'/);
  assert.doesNotMatch(storageFacilityMapSource, /this\.showError\('Storage registry unavailable'/);
  assert.match(fuelShortageSource, /Fuel shortage registry is temporarily unavailable\./);
  assert.match(fuelShortageSource, /source: 'Fuel shortage registry and market availability feeds'/);
  assert.doesNotMatch(fuelShortageSource, /this\.showError\('Fuel shortage registry unavailable'/);
  assert.match(energyDisruptionsSource, /Energy disruptions log is temporarily unavailable\./);
  assert.match(energyDisruptionsSource, /source: 'Energy disruption registry and operator evidence feeds'/);
  assert.doesNotMatch(energyDisruptionsSource, /this\.showError\('Energy disruptions log unavailable'/);
  assert.match(ucdpEventsSource, /public showExternalUnavailable\(detail\?: string\): void/);
  assert.match(ucdpEventsSource, /Conflict event registry is temporarily unavailable\./);
  assert.match(diseaseOutbreaksSource, /public showExternalUnavailable\(detail\?: string\): void/);
  assert.match(diseaseOutbreaksSource, /Disease outbreak feed is temporarily unavailable\./);
  assert.match(socialVelocitySource, /public showExternalUnavailable\(detail\?: string\): void/);
  assert.match(socialVelocitySource, /Social velocity feed is temporarily unavailable\./);
  assert.match(dataLoaderSource, /showConfigError\(t\('common\.noDataAvailable'\)\)/);
  assert.match(dataLoaderSource, /showExternalUnavailable\('Conflict event registry did not return a usable snapshot\.'\)/);
  assert.match(dataLoaderSource, /showExternalUnavailable\(error instanceof Error \? error\.message : 'Conflict event registry request failed\.'\)/);
  assert.match(dataLoaderSource, /panel\?\.updateData\(data\.outbreaks \?\? \[\]\)/);
  assert.match(dataLoaderSource, /panel\?\.showExternalUnavailable\(e instanceof Error \? e\.message : 'Disease outbreak feed request failed\.'\)/);
  assert.match(dataLoaderSource, /panel\?\.updateData\(data\.posts \?\? \[\]\)/);
  assert.match(dataLoaderSource, /panel\?\.showExternalUnavailable\(e instanceof Error \? e\.message : 'Social velocity feed request failed\.'\)/);
  assert.match(mainCss, /\.economic-empty-detail \{/);
  assert.match(mainCss, /\.panel-external-state \{/);
});

test('finance guide brief styles are defined', () => {
  assert.match(panelsCss, /\.finance-guide-brief \{/);
  assert.match(panelsCss, /\.finance-guide-brief-line \{/);
  assert.match(panelsCss, /\.portfolio-impact-section \{/);
  assert.match(panelsCss, /\.portfolio-impact-item \{/);
  assert.match(panelsCss, /padding: 6px 8px;/);
  assert.match(panelsCss, /\.portfolio-impact-item-header,/);
  assert.match(panelsCss, /gap: 6px;/);
  assert.match(panelsCss, /font-size: 10px;/);
  assert.match(panelsCss, /line-height: 1\.35;/);
  assert.match(panelsCss, /\.portfolio-impact-section-title-row \{/);
  assert.match(panelsCss, /\.idea-radar-playbook-toggle \{/);
  assert.match(panelsCss, /\.portfolio-impact-chip,/);
  assert.match(mainCss, /height: min\(32vh, 260px\) !important;/);
  assert.match(mainCss, /min-height: 160px !important;/);
  assert.match(mainCss, /\.main-content \.map-section\.collapsed \{/);
  assert.match(mainCss, /height: 40px !important;/);
  assert.match(mainCss, /\[data-variant="finance"\] \.panel \{/);
  assert.match(mainCss, /max-height: min\(54vh, 390px\);/);
  assert.match(mainCss, /\[data-variant="finance"\] \.map-section \{/);
  assert.match(mainCss, /height: 42vh;/);
  assert.match(mainCss, /\[data-variant="finance"\] \.panels-grid \{/);
  assert.match(mainCss, /grid-auto-rows: minmax\(180px, 320px\);/);
  assert.match(mainCss, /\.panels-grid \{/);
  assert.match(mainCss, /grid-template-columns: repeat\(auto-fill, minmax\(260px, 1fr\)\);/);
  assert.match(mainCss, /grid-auto-rows: minmax\(190px, 340px\);/);
  assert.match(mainCss, /\.map-section \{/);
  assert.match(mainCss, /height: 46vh;/);
  assert.match(mainCss, /min-height: 300px;/);
  assert.match(mainCss, /max-height: 78vh;/);
  assert.match(mainCss, /\[data-variant="finance"\] \.community-widget \{/);
  assert.match(mainCss, /display: none;/);
  assert.match(mainCss, /\[data-variant="finance"\] \.pro-banner \{/);
  assert.match(mainCss, /font-size: 10px;/);
  assert.match(mainCss, /padding: 4px 28px 4px 8px;/);
});

test('finance mobile skeleton prioritizes panels over a tall placeholder map', () => {
  assert.match(indexHtml, /<html lang="en" translate="no" class="notranslate">/);
  assert.match(indexHtml, /<meta name="google" content="notranslate" \/>/);
  assert.match(indexHtml, /\[data-variant="finance"\] \.skeleton-map\{/);
  assert.match(indexHtml, /height:72px;/);
  assert.match(indexHtml, /\[data-variant="finance"\] \.skeleton-map-body\{/);
  assert.match(indexHtml, /display:none;/);
  assert.match(indexHtml, /\[data-variant="finance"\] \.skeleton-panel\{/);
  assert.match(indexHtml, /height:188px;/);
  assert.match(indexHtml, /ポートフォリオ影響/);
  assert.match(indexHtml, /アイデアレーダー/);
  assert.match(indexHtml, /市場/);
  assert.match(indexHtml, /nth-child\(n\+4\)/);
});

test('market and world clock panels localize visible helper labels for Japanese users', () => {
  assert.match(panelLayoutSource, /const label = this\.getLocalizedPanelName\(panelKey, fallbackLabel\)/);
  assert.match(marketPanelSource, /\$\{ja \? 'パフォーマンス' : 'Performance'\}/);
  assert.match(marketPanelSource, /\$\{ja \? 'バリュエーション' : 'Valuations'\}/);
  assert.match(marketPanelSource, /\$\{ja \? 'セクター' : 'Sector'\}/);
  assert.match(marketPanelSource, /\$\{ja \? '年初来' : 'YTD'\}/);
  assert.match(marketPanelSource, /const firstTabLabel = ja \? 'コモディティ' : 'Commodities';/);
  assert.match(marketPanelSource, /\$\{ja \? 'ユーロ為替' : 'EUR FX'\}/);
  assert.match(marketPanelSource, /\$\{ja \? '金\/為替' : 'XAU\/FX'\}/);
  assert.match(marketPanelSource, /\$\{ja \? 'ソース' : 'Source'\}: ECB/);
  assert.match(marketPanelSource, /ja \? '暗号資産セクター' : 'Crypto Sectors'/);
  assert.match(marketPanelSource, /ja \? 'DeFiトークン' : 'DeFi Tokens'/);
  assert.match(marketPanelSource, /ja \? 'AIトークン' : 'AI Tokens'/);
  assert.match(marketPanelSource, /ja \? 'アルトトークン' : 'Alt Tokens'/);
  assert.match(worldClockSource, /title: getCurrentLanguage\(\) === 'ja' \? '世界時計' : 'World Clock'/);
  assert.match(worldClockSource, /getCurrentLanguage\(\) === 'ja' \? '都市を選択' : 'Select cities'/);
  assert.match(worldClockSource, /\$\{ja \? '取引中' : 'OPEN'\}/);
  assert.match(worldClockSource, /\$\{ja \? '終了' : 'CLSD'\}/);
  assert.match(worldClockSource, /'南北アメリカ'/);
  assert.match(worldClockSource, /'欧州'/);
  assert.match(worldClockSource, /'アジア太平洋'/);
  assert.match(watchlistModalSource, /ja \? '市場ウォッチリスト' : 'Market watchlist'/);
  assert.match(watchlistModalSource, /ja \? '監視銘柄' : 'Watchlist'/);
  assert.match(macroTilesSource, /ja \? 'マクロ指標' : 'Macro Indicators'/);
  assert.match(breakthroughsSource, /ja \? 'ブレークスルー' : 'Breakthroughs'/);
  assert.match(speciesSource, /ja \? '保全の成果' : 'Conservation Wins'/);
  assert.match(speciesSource, /保全データはまだありません/);
  assert.match(economicCalendarTitleSource, /ja \? '経済カレンダー' : 'Economic Calendar'/);
  assert.match(renewableSource, /ja \? '再生可能エネルギー' : 'Renewable Energy'/);
  assert.match(cotTitleSource, /ja \? 'CFTC 建玉ポジション' : 'CFTC COT Positioning'/);
  assert.match(aaiiTitleSource, /ja \? 'AAII 投資家センチメント' : 'AAII Investor Sentiment'/);
  assert.match(socialVelocityTitleSource, /ja \? 'ソーシャルベロシティ' : 'Social Velocity'/);
  assert.match(energyRiskOverviewSource, /ja \? 'グローバルエネルギーリスク概観' : 'Global Energy Risk Overview'/);
  assert.match(energyDisruptionsSource, /ja \? 'エネルギー障害ログ' : 'Energy Disruptions Log'/);
  assert.match(energyCrisisSource, /ja \? 'エネルギー危機トラッカー' : 'Energy Crisis Tracker'/);
  assert.match(fuelShortageSource, /ja \? '世界燃料不足レジストリ' : 'Global Fuel Shortage Registry'/);
  assert.match(pipelineStatusSource, /ja \? '石油・ガス パイプライン状況' : 'Oil & Gas Pipeline Status'/);
  assert.match(storageFacilityMapSource, /ja \? '戦略備蓄アトラス' : 'Strategic Storage Atlas'/);
  assert.match(forecastSource, /ja \? 'AI 予測' : 'AI Forecasts'/);
  assert.match(jaLocale, /"forex": "外国為替・通貨"/);
  assert.match(jaLocale, /"bonds": "債券・金利"/);
  assert.match(jaLocale, /"cryptoHeatmap": "暗号資産セクター"/);
  assert.match(jaLocale, /"breakthroughs": "ブレークスルー"/);
  assert.match(jaLocale, /"species": "保全の成果"/);
  assert.match(jaLocale, /"macroTiles": "マクロ指標"/);
  assert.match(enLocale, /"forex": "Forex & Currencies"/);
  assert.match(enLocale, /"bonds": "Fixed Income"/);
});

test('finance desktop skeleton reduces map dominance and labels core panels', () => {
  assert.match(indexHtml, /@media \(min-width: 861px\)/);
  assert.match(indexHtml, /\[data-variant="finance"\] \.skeleton-map\{/);
  assert.match(indexHtml, /height:40vh;/);
  assert.match(indexHtml, /min-height:240px;/);
  assert.match(indexHtml, /max-height:420px;/);
  assert.match(indexHtml, /マクロ指標/);
  assert.match(indexHtml, /ライブニュース/);
});
