FROM node:26-alpine@sha256:725aeba2364a9b16beae49e180d83bd597dbd0b15c47f1f28875c290bfd255b9
WORKDIR /app
RUN npm init -y && npm install redis@4
COPY redis-rest-proxy.mjs .
EXPOSE 80
CMD ["node", "redis-rest-proxy.mjs"]
