---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hlidskjalf-monitor-sa
  namespace: hlidskjalf-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hlidskjalf-job-reader
  namespace: hlidskjalf-monitor
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hlidskjalf-monitor-sa-job-reader
  namespace: hlidskjalf-monitor
subjects:
  - kind: ServiceAccount
    name: hlidskjalf-monitor-sa
    namespace: hlidskjalf-monitor
roleRef:
  kind: Role
  name: hlidskjalf-job-reader
  apiGroup: rbac.authorization.k8s.io
