apiVersion: v1
kind: Secret
metadata:
  name: hlidskjalf-secrets
  namespace: hlidskjalf-monitor
type: Opaque
stringData:
  SLACK_ALERTS_WEBHOOK: ""
  SLACK_BRIEFING_WEBHOOK: ""
  SLACK_DRAUPNIR_WEBHOOK: ""
  FINNHUB_API_KEY: ""
  ACLED_API_KEY: ""
  TELEGRAM_SESSION: ""
  UPSTASH_REDIS_REST_URL: ""
  UPSTASH_REDIS_REST_TOKEN: ""
  REDIS_URL: "redis://localhost:6379"
