apiVersion: v1
kind: Service
metadata:
  name: hlidskjalf-server-svc
  namespace: hlidskjalf-monitor
spec:
  selector:
    app: hlidskjalf-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: hlidskjalf-monitor
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
