export interface InspiringQuote {
  id: string;
  text: string;
  author: string;
  source: string;
  reference: string;
  tags: string[];
  translation?: string;
}

export const STOIC_QUOTES = [
  {
    id: 'stoic-01',
    text: 'Men are disturbed not by things, but by the views which they take of things.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter V',
    tags: ['Perspective', 'Calm', 'Self-command'],
  },
  {
    id: 'stoic-02',
    text: 'Demand not that events should happen as you wish; but wish them to happen as they do happen, and you will go on well.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter VIII',
    tags: ['Acceptance', 'Resilience', 'Steadiness'],
  },
  {
    id: 'stoic-03',
    text: 'Upon every accident, remember to turn toward yourself and inquire what faculty you have for its use.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter X',
    tags: ['Discipline', 'Response', 'Clarity'],
  },
  {
    id: 'stoic-04',
    text: 'Never say of anything, "I have lost it," but, "I have restored it."',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter XI',
    tags: ['Detachment', 'Gratitude', 'Perspective'],
  },
  {
    id: 'stoic-05',
    text: 'If you would improve, lay aside such reasonings as these: "If I neglect my affairs, I shall not have a maintenance."',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter XII',
    tags: ['Improvement', 'Courage', 'Priorities'],
  },
  {
    id: 'stoic-06',
    text: 'If you would improve, be content to be thought foolish and dull with regard to externals.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter XIII',
    tags: ['Humility', 'Freedom', 'Discipline'],
  },
  {
    id: 'stoic-07',
    text: 'Remember that you are an actor in a drama of such sort as the Author chooses.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter XVII',
    tags: ['Duty', 'Calling', 'Acceptance'],
  },
  {
    id: 'stoic-08',
    text: 'You can be unconquerable if you enter into no combat in which it is not in your own power to conquer.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter XIX',
    tags: ['Freedom', 'Focus', 'Agency'],
  },
  {
    id: 'stoic-09',
    text: 'Remember that it is not he who gives abuse or blows, who affronts, but the view we take of these things as insulting.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter XX',
    tags: ['Composure', 'Interpretation', 'Self-command'],
  },
  {
    id: 'stoic-10',
    text: 'Everything has two handles: one by which it may be borne, another by which it cannot.',
    author: 'Epictetus',
    source: 'Enchiridion',
    reference: 'Chapter XLIII',
    tags: ['Perspective', 'Mercy', 'Endurance'],
  },
  {
    id: 'stoic-11',
    text: 'In the morning when thou findest thyself unwilling to rise, consider with thyself presently, it is to go about a man\'s work that I am stirred up.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book V',
    tags: ['Purpose', 'Duty', 'Morning'],
  },
  {
    id: 'stoic-12',
    text: 'Such as thy thoughts and ordinary cogitations are, such will thy mind be in time.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book V',
    tags: ['Mindset', 'Inner life', 'Formation'],
  },
  {
    id: 'stoic-13',
    text: 'The best kind of revenge is, not to become like unto them.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book VI',
    tags: ['Mercy', 'Character', 'Restraint'],
  },
  {
    id: 'stoic-14',
    text: 'Thou must be like a promontory of the sea, against which though the waves beat continually, yet it both itself stands, and about it are those swelling waves stilled and quieted.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book IV',
    tags: ['Steadiness', 'Storms', 'Fortitude'],
  },
  {
    id: 'stoic-15',
    text: 'Oh, wretched I, to whom this mischance is happened! nay, happy I, to whom this thing being happened, I can continue without grief.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book IV',
    tags: ['Adversity', 'Courage', 'Reframing'],
  },
  {
    id: 'stoic-16',
    text: 'Whatsoever any man either doth or saith, thou must be good.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book VII',
    tags: ['Goodness', 'Integrity', 'Constancy'],
  },
  {
    id: 'stoic-17',
    text: 'Fancy not to thyself things future, as though they were present.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book VII',
    tags: ['Presence', 'Calm', 'Attention'],
  },
  {
    id: 'stoic-18',
    text: 'This time that is now present, bestow thou upon thyself.',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    reference: 'Book VIII',
    tags: ['Presence', 'Time', 'Self-rule'],
  },
] satisfies readonly InspiringQuote[];

export const BIBLICAL_QUOTES = [
  {
    id: 'bible-01',
    text: 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.',
    author: 'Moses',
    source: 'Deuteronomy',
    reference: '31:6',
    translation: 'KJV',
    tags: ['Courage', 'Presence', 'Perseverance'],
  },
  {
    id: 'bible-02',
    text: 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.',
    author: 'The LORD to Joshua',
    source: 'Joshua',
    reference: '1:9',
    translation: 'KJV',
    tags: ['Courage', 'Calling', 'Presence'],
  },
  {
    id: 'bible-03',
    text: 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?',
    author: 'David',
    source: 'Psalms',
    reference: '27:1',
    translation: 'KJV',
    tags: ['Fearlessness', 'Strength', 'Hope'],
  },
  {
    id: 'bible-04',
    text: 'Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.',
    author: 'David',
    source: 'Psalms',
    reference: '27:14',
    translation: 'KJV',
    tags: ['Patience', 'Courage', 'Strength'],
  },
  {
    id: 'bible-05',
    text: 'The righteous cry, and the LORD heareth, and delivereth them out of all their troubles.',
    author: 'David',
    source: 'Psalms',
    reference: '34:17',
    translation: 'KJV',
    tags: ['Prayer', 'Deliverance', 'Comfort'],
  },
  {
    id: 'bible-06',
    text: 'God is our refuge and strength, a very present help in trouble.',
    author: 'Sons of Korah',
    source: 'Psalms',
    reference: '46:1',
    translation: 'KJV',
    tags: ['Refuge', 'Strength', 'Trouble'],
  },
  {
    id: 'bible-07',
    text: 'Be still, and know that I am God.',
    author: 'The LORD',
    source: 'Psalms',
    reference: '46:10',
    translation: 'KJV',
    tags: ['Stillness', 'Trust', 'Presence'],
  },
  {
    id: 'bible-08',
    text: 'Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.',
    author: 'David',
    source: 'Psalms',
    reference: '55:22',
    translation: 'KJV',
    tags: ['Burden', 'Support', 'Steadiness'],
  },
  {
    id: 'bible-09',
    text: 'What time I am afraid, I will trust in thee.',
    author: 'David',
    source: 'Psalms',
    reference: '56:3',
    translation: 'KJV',
    tags: ['Fear', 'Trust', 'Simplicity'],
  },
  {
    id: 'bible-10',
    text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.',
    author: 'Solomon',
    source: 'Proverbs',
    reference: '3:5-6',
    translation: 'KJV',
    tags: ['Trust', 'Guidance', 'Wisdom'],
  },
  {
    id: 'bible-11',
    text: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.',
    author: 'The LORD',
    source: 'Isaiah',
    reference: '41:10',
    translation: 'KJV',
    tags: ['Presence', 'Strength', 'Help'],
  },
  {
    id: 'bible-12',
    text: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
    author: 'Isaiah',
    source: 'Isaiah',
    reference: '40:31',
    translation: 'KJV',
    tags: ['Strength', 'Renewal', 'Endurance'],
  },
  {
    id: 'bible-13',
    text: 'When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee.',
    author: 'The LORD',
    source: 'Isaiah',
    reference: '43:2',
    translation: 'KJV',
    tags: ['Presence', 'Trials', 'Protection'],
  },
  {
    id: 'bible-14',
    text: 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.',
    author: 'The LORD',
    source: 'Jeremiah',
    reference: '29:11',
    translation: 'KJV',
    tags: ['Hope', 'Future', 'Peace'],
  },
  {
    id: 'bible-15',
    text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
    author: 'Jesus',
    source: 'Matthew',
    reference: '11:28',
    translation: 'KJV',
    tags: ['Rest', 'Invitation', 'Mercy'],
  },
  {
    id: 'bible-16',
    text: 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.',
    author: 'Jesus',
    source: 'John',
    reference: '14:27',
    translation: 'KJV',
    tags: ['Peace', 'Comfort', 'Fearlessness'],
  },
  {
    id: 'bible-17',
    text: 'These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.',
    author: 'Jesus',
    source: 'John',
    reference: '16:33',
    translation: 'KJV',
    tags: ['Peace', 'Tribulation', 'Victory'],
  },
  {
    id: 'bible-18',
    text: 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
    author: 'Paul',
    source: 'Philippians',
    reference: '4:6-7',
    translation: 'KJV',
    tags: ['Prayer', 'Peace', 'Thanksgiving'],
  },
  {
    id: 'bible-19',
    text: 'I can do all things through Christ which strengtheneth me.',
    author: 'Paul',
    source: 'Philippians',
    reference: '4:13',
    translation: 'KJV',
    tags: ['Strength', 'Confidence', 'Endurance'],
  },
  {
    id: 'bible-20',
    text: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.',
    author: 'Paul',
    source: 'Romans',
    reference: '8:28',
    translation: 'KJV',
    tags: ['Providence', 'Purpose', 'Hope'],
  },
] satisfies readonly InspiringQuote[];

export function getInitialQuoteIndex(panelId: string, totalQuotes: number, now = Date.now()): number {
  if (totalQuotes <= 0) return 0;
  const salt = [...panelId].reduce((sum, char, index) => sum + char.charCodeAt(0) * (index + 1), 0);
  const halfHourBucket = Math.floor(now / (30 * 60 * 1000));
  return (halfHourBucket + salt) % totalQuotes;
}
