// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/sebuf/http/annotations.proto

package http

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HttpMethod specifies the HTTP verb for an RPC method
type HttpMethod int32

const (
	// Unspecified defaults to POST for backward compatibility
	HttpMethod_HTTP_METHOD_UNSPECIFIED HttpMethod = 0
	HttpMethod_HTTP_METHOD_GET         HttpMethod = 1
	HttpMethod_HTTP_METHOD_POST        HttpMethod = 2
	HttpMethod_HTTP_METHOD_PUT         HttpMethod = 3
	HttpMethod_HTTP_METHOD_DELETE      HttpMethod = 4
	HttpMethod_HTTP_METHOD_PATCH       HttpMethod = 5
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "HTTP_METHOD_UNSPECIFIED",
		1: "HTTP_METHOD_GET",
		2: "HTTP_METHOD_POST",
		3: "HTTP_METHOD_PUT",
		4: "HTTP_METHOD_DELETE",
		5: "HTTP_METHOD_PATCH",
	}
	HttpMethod_value = map[string]int32{
		"HTTP_METHOD_UNSPECIFIED": 0,
		"HTTP_METHOD_GET":         1,
		"HTTP_METHOD_POST":        2,
		"HTTP_METHOD_PUT":         3,
		"HTTP_METHOD_DELETE":      4,
		"HTTP_METHOD_PATCH":       5,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sebuf_http_annotations_proto_enumTypes[0].Descriptor()
}

func (HttpMethod) Type() protoreflect.EnumType {
	return &file_proto_sebuf_http_annotations_proto_enumTypes[0]
}

func (x HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpMethod.Descriptor instead.
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{0}
}

// Int64Encoding controls how int64/uint64 fields serialize to JSON
type Int64Encoding int32

const (
	// Follow protojson default (serialize as string)
	Int64Encoding_INT64_ENCODING_UNSPECIFIED Int64Encoding = 0
	// Explicit string encoding: "12345"
	Int64Encoding_INT64_ENCODING_STRING Int64Encoding = 1
	// Numeric encoding: 12345 (precision warning for values > 2^53)
	Int64Encoding_INT64_ENCODING_NUMBER Int64Encoding = 2
)

// Enum value maps for Int64Encoding.
var (
	Int64Encoding_name = map[int32]string{
		0: "INT64_ENCODING_UNSPECIFIED",
		1: "INT64_ENCODING_STRING",
		2: "INT64_ENCODING_NUMBER",
	}
	Int64Encoding_value = map[string]int32{
		"INT64_ENCODING_UNSPECIFIED": 0,
		"INT64_ENCODING_STRING":      1,
		"INT64_ENCODING_NUMBER":      2,
	}
)

func (x Int64Encoding) Enum() *Int64Encoding {
	p := new(Int64Encoding)
	*p = x
	return p
}

func (x Int64Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Int64Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sebuf_http_annotations_proto_enumTypes[1].Descriptor()
}

func (Int64Encoding) Type() protoreflect.EnumType {
	return &file_proto_sebuf_http_annotations_proto_enumTypes[1]
}

func (x Int64Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Int64Encoding.Descriptor instead.
func (Int64Encoding) EnumDescriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{1}
}

// EnumEncoding controls how enum fields serialize to JSON
type EnumEncoding int32

const (
	// Follow protojson default (serialize as proto name string)
	EnumEncoding_ENUM_ENCODING_UNSPECIFIED EnumEncoding = 0
	// Explicit string encoding: "STATUS_ACTIVE"
	EnumEncoding_ENUM_ENCODING_STRING EnumEncoding = 1
	// Numeric encoding: 1
	EnumEncoding_ENUM_ENCODING_NUMBER EnumEncoding = 2
)

// Enum value maps for EnumEncoding.
var (
	EnumEncoding_name = map[int32]string{
		0: "ENUM_ENCODING_UNSPECIFIED",
		1: "ENUM_ENCODING_STRING",
		2: "ENUM_ENCODING_NUMBER",
	}
	EnumEncoding_value = map[string]int32{
		"ENUM_ENCODING_UNSPECIFIED": 0,
		"ENUM_ENCODING_STRING":      1,
		"ENUM_ENCODING_NUMBER":      2,
	}
)

func (x EnumEncoding) Enum() *EnumEncoding {
	p := new(EnumEncoding)
	*p = x
	return p
}

func (x EnumEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sebuf_http_annotations_proto_enumTypes[2].Descriptor()
}

func (EnumEncoding) Type() protoreflect.EnumType {
	return &file_proto_sebuf_http_annotations_proto_enumTypes[2]
}

func (x EnumEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumEncoding.Descriptor instead.
func (EnumEncoding) EnumDescriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{2}
}

// EmptyBehavior controls how empty message fields serialize to JSON.
// "Empty" means all fields at proto default (proto.Size() == 0).
type EmptyBehavior int32

const (
	// Follow default behavior: serialize empty messages as {} (same as PRESERVE)
	EmptyBehavior_EMPTY_BEHAVIOR_UNSPECIFIED EmptyBehavior = 0
	// Serialize empty messages as {} (explicit same as default)
	EmptyBehavior_EMPTY_BEHAVIOR_PRESERVE EmptyBehavior = 1
	// Serialize empty messages as null
	EmptyBehavior_EMPTY_BEHAVIOR_NULL EmptyBehavior = 2
	// Omit the field entirely when message is empty
	EmptyBehavior_EMPTY_BEHAVIOR_OMIT EmptyBehavior = 3
)

// Enum value maps for EmptyBehavior.
var (
	EmptyBehavior_name = map[int32]string{
		0: "EMPTY_BEHAVIOR_UNSPECIFIED",
		1: "EMPTY_BEHAVIOR_PRESERVE",
		2: "EMPTY_BEHAVIOR_NULL",
		3: "EMPTY_BEHAVIOR_OMIT",
	}
	EmptyBehavior_value = map[string]int32{
		"EMPTY_BEHAVIOR_UNSPECIFIED": 0,
		"EMPTY_BEHAVIOR_PRESERVE":    1,
		"EMPTY_BEHAVIOR_NULL":        2,
		"EMPTY_BEHAVIOR_OMIT":        3,
	}
)

func (x EmptyBehavior) Enum() *EmptyBehavior {
	p := new(EmptyBehavior)
	*p = x
	return p
}

func (x EmptyBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmptyBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sebuf_http_annotations_proto_enumTypes[3].Descriptor()
}

func (EmptyBehavior) Type() protoreflect.EnumType {
	return &file_proto_sebuf_http_annotations_proto_enumTypes[3]
}

func (x EmptyBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmptyBehavior.Descriptor instead.
func (EmptyBehavior) EnumDescriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{3}
}

// TimestampFormat controls how google.protobuf.Timestamp fields serialize to JSON.
type TimestampFormat int32

const (
	// Follow protojson default (RFC 3339 string: "2024-01-15T09:30:00Z")
	TimestampFormat_TIMESTAMP_FORMAT_UNSPECIFIED TimestampFormat = 0
	// Explicit RFC 3339 (same as default but self-documenting)
	TimestampFormat_TIMESTAMP_FORMAT_RFC3339 TimestampFormat = 1
	// Unix seconds as integer: 1705312200 (nanos truncated)
	TimestampFormat_TIMESTAMP_FORMAT_UNIX_SECONDS TimestampFormat = 2
	// Unix milliseconds as integer: 1705312200000 (sub-millisecond nanos truncated)
	TimestampFormat_TIMESTAMP_FORMAT_UNIX_MILLIS TimestampFormat = 3
	// Date-only string: "2024-01-15" (time component dropped, lossy)
	TimestampFormat_TIMESTAMP_FORMAT_DATE TimestampFormat = 4
)

// Enum value maps for TimestampFormat.
var (
	TimestampFormat_name = map[int32]string{
		0: "TIMESTAMP_FORMAT_UNSPECIFIED",
		1: "TIMESTAMP_FORMAT_RFC3339",
		2: "TIMESTAMP_FORMAT_UNIX_SECONDS",
		3: "TIMESTAMP_FORMAT_UNIX_MILLIS",
		4: "TIMESTAMP_FORMAT_DATE",
	}
	TimestampFormat_value = map[string]int32{
		"TIMESTAMP_FORMAT_UNSPECIFIED":  0,
		"TIMESTAMP_FORMAT_RFC3339":      1,
		"TIMESTAMP_FORMAT_UNIX_SECONDS": 2,
		"TIMESTAMP_FORMAT_UNIX_MILLIS":  3,
		"TIMESTAMP_FORMAT_DATE":         4,
	}
)

func (x TimestampFormat) Enum() *TimestampFormat {
	p := new(TimestampFormat)
	*p = x
	return p
}

func (x TimestampFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimestampFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sebuf_http_annotations_proto_enumTypes[4].Descriptor()
}

func (TimestampFormat) Type() protoreflect.EnumType {
	return &file_proto_sebuf_http_annotations_proto_enumTypes[4]
}

func (x TimestampFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimestampFormat.Descriptor instead.
func (TimestampFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{4}
}

// BytesEncoding controls how bytes fields serialize to JSON.
type BytesEncoding int32

const (
	// Follow protojson default (standard base64 with padding)
	BytesEncoding_BYTES_ENCODING_UNSPECIFIED BytesEncoding = 0
	// Standard base64 with padding (RFC 4648): "SGVsbG8="
	BytesEncoding_BYTES_ENCODING_BASE64 BytesEncoding = 1
	// Base64 without padding: "SGVsbG8"
	BytesEncoding_BYTES_ENCODING_BASE64_RAW BytesEncoding = 2
	// URL-safe base64 with padding: "SGVsbG8="
	BytesEncoding_BYTES_ENCODING_BASE64URL BytesEncoding = 3
	// URL-safe base64 without padding: "SGVsbG8"
	BytesEncoding_BYTES_ENCODING_BASE64URL_RAW BytesEncoding = 4
	// Hexadecimal encoding (lowercase): "48656c6c6f"
	BytesEncoding_BYTES_ENCODING_HEX BytesEncoding = 5
)

// Enum value maps for BytesEncoding.
var (
	BytesEncoding_name = map[int32]string{
		0: "BYTES_ENCODING_UNSPECIFIED",
		1: "BYTES_ENCODING_BASE64",
		2: "BYTES_ENCODING_BASE64_RAW",
		3: "BYTES_ENCODING_BASE64URL",
		4: "BYTES_ENCODING_BASE64URL_RAW",
		5: "BYTES_ENCODING_HEX",
	}
	BytesEncoding_value = map[string]int32{
		"BYTES_ENCODING_UNSPECIFIED":   0,
		"BYTES_ENCODING_BASE64":        1,
		"BYTES_ENCODING_BASE64_RAW":    2,
		"BYTES_ENCODING_BASE64URL":     3,
		"BYTES_ENCODING_BASE64URL_RAW": 4,
		"BYTES_ENCODING_HEX":           5,
	}
)

func (x BytesEncoding) Enum() *BytesEncoding {
	p := new(BytesEncoding)
	*p = x
	return p
}

func (x BytesEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BytesEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sebuf_http_annotations_proto_enumTypes[5].Descriptor()
}

func (BytesEncoding) Type() protoreflect.EnumType {
	return &file_proto_sebuf_http_annotations_proto_enumTypes[5]
}

func (x BytesEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BytesEncoding.Descriptor instead.
func (BytesEncoding) EnumDescriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{5}
}

// HttpConfig defines HTTP-specific configuration for an RPC method
type HttpConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The HTTP path for this method (supports path variables like /users/{id})
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The HTTP method (GET, POST, PUT, DELETE, PATCH). Defaults to POST if unspecified.
	Method        HttpMethod `protobuf:"varint,2,opt,name=method,proto3,enum=sebuf.http.HttpMethod" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpConfig) Reset() {
	*x = HttpConfig{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpConfig) ProtoMessage() {}

func (x *HttpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpConfig.ProtoReflect.Descriptor instead.
func (*HttpConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *HttpConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpConfig) GetMethod() HttpMethod {
	if x != nil {
		return x.Method
	}
	return HttpMethod_HTTP_METHOD_UNSPECIFIED
}

// ServiceConfig defines HTTP-specific configuration for an entire service
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base path prefix for all methods in this service
	BasePath      string `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceConfig) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

// FieldExamples defines example values for a field
type FieldExamples struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of example values for this field
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldExamples) Reset() {
	*x = FieldExamples{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldExamples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldExamples) ProtoMessage() {}

func (x *FieldExamples) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldExamples.ProtoReflect.Descriptor instead.
func (*FieldExamples) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *FieldExamples) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// QueryConfig defines query parameter configuration for a message field
type QueryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The query parameter name in the URL (e.g., "page_size" for ?page_size=10)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether this query parameter is required
	Required      bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConfig) Reset() {
	*x = QueryConfig{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConfig) ProtoMessage() {}

func (x *QueryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConfig.ProtoReflect.Descriptor instead.
func (*QueryConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *QueryConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryConfig) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// OneofConfig controls oneof serialization as a discriminated union.
// Applied to a oneof definition via (sebuf.http.oneof_config).
type OneofConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON field name for the discriminator (e.g., "type", "kind").
	// Required: if empty, the annotation is ignored.
	Discriminator string `protobuf:"bytes,1,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	// Whether to flatten variant message fields to the same level as the discriminator.
	// When true: variant's child fields are promoted to the parent object alongside the discriminator.
	// When false: variant stays nested under its field name with the discriminator alongside.
	// Requires all variant fields to be message types when true.
	Flatten       bool `protobuf:"varint,2,opt,name=flatten,proto3" json:"flatten,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofConfig) Reset() {
	*x = OneofConfig{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofConfig) ProtoMessage() {}

func (x *OneofConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofConfig.ProtoReflect.Descriptor instead.
func (*OneofConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *OneofConfig) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

func (x *OneofConfig) GetFlatten() bool {
	if x != nil {
		return x.Flatten
	}
	return false
}

var file_proto_sebuf_http_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpConfig)(nil),
		Field:         50003,
		Name:          "sebuf.http.config",
		Tag:           "bytes,50003,opt,name=config",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceConfig)(nil),
		Field:         50004,
		Name:          "sebuf.http.service_config",
		Tag:           "bytes,50004,opt,name=service_config",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofConfig)(nil),
		Field:         50017,
		Name:          "sebuf.http.oneof_config",
		Tag:           "bytes,50017,opt,name=oneof_config",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldExamples)(nil),
		Field:         50007,
		Name:          "sebuf.http.field_examples",
		Tag:           "bytes,50007,opt,name=field_examples",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*QueryConfig)(nil),
		Field:         50008,
		Name:          "sebuf.http.query",
		Tag:           "bytes,50008,opt,name=query",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50009,
		Name:          "sebuf.http.unwrap",
		Tag:           "varint,50009,opt,name=unwrap",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Int64Encoding)(nil),
		Field:         50010,
		Name:          "sebuf.http.int64_encoding",
		Tag:           "varint,50010,opt,name=int64_encoding,enum=sebuf.http.Int64Encoding",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*EnumEncoding)(nil),
		Field:         50011,
		Name:          "sebuf.http.enum_encoding",
		Tag:           "varint,50011,opt,name=enum_encoding,enum=sebuf.http.EnumEncoding",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50013,
		Name:          "sebuf.http.nullable",
		Tag:           "varint,50013,opt,name=nullable",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*EmptyBehavior)(nil),
		Field:         50014,
		Name:          "sebuf.http.empty_behavior",
		Tag:           "varint,50014,opt,name=empty_behavior,enum=sebuf.http.EmptyBehavior",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*TimestampFormat)(nil),
		Field:         50015,
		Name:          "sebuf.http.timestamp_format",
		Tag:           "varint,50015,opt,name=timestamp_format,enum=sebuf.http.TimestampFormat",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*BytesEncoding)(nil),
		Field:         50016,
		Name:          "sebuf.http.bytes_encoding",
		Tag:           "varint,50016,opt,name=bytes_encoding,enum=sebuf.http.BytesEncoding",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50018,
		Name:          "sebuf.http.oneof_value",
		Tag:           "bytes,50018,opt,name=oneof_value",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50019,
		Name:          "sebuf.http.flatten",
		Tag:           "varint,50019,opt,name=flatten",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50020,
		Name:          "sebuf.http.flatten_prefix",
		Tag:           "bytes,50020,opt,name=flatten_prefix",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50012,
		Name:          "sebuf.http.enum_value",
		Tag:           "bytes,50012,opt,name=enum_value",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional sebuf.http.HttpConfig config = 50003;
	E_Config = &file_proto_sebuf_http_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional sebuf.http.ServiceConfig service_config = 50004;
	E_ServiceConfig = &file_proto_sebuf_http_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// Controls oneof serialization as a discriminated union.
	// When set, adds a discriminator field to the JSON output identifying which variant is set.
	//
	// optional sebuf.http.OneofConfig oneof_config = 50017;
	E_OneofConfig = &file_proto_sebuf_http_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Example values for documentation/OpenAPI
	//
	// optional sebuf.http.FieldExamples field_examples = 50007;
	E_FieldExamples = &file_proto_sebuf_http_annotations_proto_extTypes[3]
	// Query parameter configuration for a field
	//
	// optional sebuf.http.QueryConfig query = 50008;
	E_Query = &file_proto_sebuf_http_annotations_proto_extTypes[4]
	// Mark a repeated field for unwrapping when parent message is a map value.
	// When set to true on a repeated field, and the message containing this field
	// is used as a map value, the JSON serialization will collapse the wrapper
	// to just the unwrapped field's array value.
	// Constraints: Only valid on repeated fields, only one per message.
	//
	// optional bool unwrap = 50009;
	E_Unwrap = &file_proto_sebuf_http_annotations_proto_extTypes[5]
	// Controls int64/uint64 JSON encoding for this field.
	// Valid on: int64, sint64, sfixed64, uint64, fixed64 fields.
	// Default: STRING encoding (protojson default for JavaScript precision safety).
	//
	// optional sebuf.http.Int64Encoding int64_encoding = 50010;
	E_Int64Encoding = &file_proto_sebuf_http_annotations_proto_extTypes[6]
	// Controls enum JSON encoding for this field.
	// Valid on: enum fields only.
	// Default: STRING encoding (protojson default using proto enum names).
	//
	// optional sebuf.http.EnumEncoding enum_encoding = 50011;
	E_EnumEncoding = &file_proto_sebuf_http_annotations_proto_extTypes[7]
	// Mark a primitive field as nullable (explicit null vs absent).
	// Only valid on proto3 optional fields (HasOptionalKeyword=true).
	// When true: unset field serializes as null, set field serializes normally.
	// When false (default): unset field is omitted from JSON.
	//
	// optional bool nullable = 50013;
	E_Nullable = &file_proto_sebuf_http_annotations_proto_extTypes[8]
	// Controls how empty message fields serialize to JSON.
	// Only valid on singular message fields (not repeated, not map).
	// "Empty" = all fields at proto default (proto.Size() == 0).
	//
	// optional sebuf.http.EmptyBehavior empty_behavior = 50014;
	E_EmptyBehavior = &file_proto_sebuf_http_annotations_proto_extTypes[9]
	// Controls timestamp JSON encoding for this field.
	// Valid on: google.protobuf.Timestamp fields only.
	// Default: RFC3339 (protojson default).
	//
	// optional sebuf.http.TimestampFormat timestamp_format = 50015;
	E_TimestampFormat = &file_proto_sebuf_http_annotations_proto_extTypes[10]
	// Controls bytes JSON encoding for this field.
	// Valid on: bytes fields only.
	// Default: BASE64 (protojson default).
	//
	// optional sebuf.http.BytesEncoding bytes_encoding = 50016;
	E_BytesEncoding = &file_proto_sebuf_http_annotations_proto_extTypes[11]
	// Custom discriminator value for this oneof variant field.
	// When set, this value is used in the discriminator field instead of the proto field name.
	// Only valid on fields that are part of a oneof with oneof_config annotation.
	//
	// optional string oneof_value = 50018;
	E_OneofValue = &file_proto_sebuf_http_annotations_proto_extTypes[12]
	// Flatten a nested message field, promoting its child fields to the parent level in JSON.
	// Only valid on singular message fields (not repeated, not map, not oneof variant).
	// When true: child message fields appear at the parent level (e.g., address.street becomes street).
	//
	// optional bool flatten = 50019;
	E_Flatten = &file_proto_sebuf_http_annotations_proto_extTypes[13]
	// Prefix to prepend to flattened field names to avoid collisions.
	// Only valid when flatten=true is also set.
	// Example: flatten_prefix="billing_" with child field "street" produces "billing_street" in JSON.
	//
	// optional string flatten_prefix = 50020;
	E_FlattenPrefix = &file_proto_sebuf_http_annotations_proto_extTypes[14]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Custom JSON string for this enum value (e.g., "active" instead of "STATUS_ACTIVE").
	// When set, this value is used for JSON serialization instead of the proto name.
	// Combines with enum_encoding=STRING on fields using this enum.
	//
	// optional string enum_value = 50012;
	E_EnumValue = &file_proto_sebuf_http_annotations_proto_extTypes[15]
)

var File_proto_sebuf_http_annotations_proto protoreflect.FileDescriptor

const file_proto_sebuf_http_annotations_proto_rawDesc = "" +
	"\n" +
	"\"proto/sebuf/http/annotations.proto\x12\n" +
	"sebuf.http\x1a google/protobuf/descriptor.proto\"P\n" +
	"\n" +
	"HttpConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12.\n" +
	"\x06method\x18\x02 \x01(\x0e2\x16.sebuf.http.HttpMethodR\x06method\",\n" +
	"\rServiceConfig\x12\x1b\n" +
	"\tbase_path\x18\x01 \x01(\tR\bbasePath\"'\n" +
	"\rFieldExamples\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"=\n" +
	"\vQueryConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\"M\n" +
	"\vOneofConfig\x12$\n" +
	"\rdiscriminator\x18\x01 \x01(\tR\rdiscriminator\x12\x18\n" +
	"\aflatten\x18\x02 \x01(\bR\aflatten*\x98\x01\n" +
	"\n" +
	"HttpMethod\x12\x1b\n" +
	"\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHTTP_METHOD_GET\x10\x01\x12\x14\n" +
	"\x10HTTP_METHOD_POST\x10\x02\x12\x13\n" +
	"\x0fHTTP_METHOD_PUT\x10\x03\x12\x16\n" +
	"\x12HTTP_METHOD_DELETE\x10\x04\x12\x15\n" +
	"\x11HTTP_METHOD_PATCH\x10\x05*e\n" +
	"\rInt64Encoding\x12\x1e\n" +
	"\x1aINT64_ENCODING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15INT64_ENCODING_STRING\x10\x01\x12\x19\n" +
	"\x15INT64_ENCODING_NUMBER\x10\x02*a\n" +
	"\fEnumEncoding\x12\x1d\n" +
	"\x19ENUM_ENCODING_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ENUM_ENCODING_STRING\x10\x01\x12\x18\n" +
	"\x14ENUM_ENCODING_NUMBER\x10\x02*~\n" +
	"\rEmptyBehavior\x12\x1e\n" +
	"\x1aEMPTY_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EMPTY_BEHAVIOR_PRESERVE\x10\x01\x12\x17\n" +
	"\x13EMPTY_BEHAVIOR_NULL\x10\x02\x12\x17\n" +
	"\x13EMPTY_BEHAVIOR_OMIT\x10\x03*\xb1\x01\n" +
	"\x0fTimestampFormat\x12 \n" +
	"\x1cTIMESTAMP_FORMAT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TIMESTAMP_FORMAT_RFC3339\x10\x01\x12!\n" +
	"\x1dTIMESTAMP_FORMAT_UNIX_SECONDS\x10\x02\x12 \n" +
	"\x1cTIMESTAMP_FORMAT_UNIX_MILLIS\x10\x03\x12\x19\n" +
	"\x15TIMESTAMP_FORMAT_DATE\x10\x04*\xc1\x01\n" +
	"\rBytesEncoding\x12\x1e\n" +
	"\x1aBYTES_ENCODING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BYTES_ENCODING_BASE64\x10\x01\x12\x1d\n" +
	"\x19BYTES_ENCODING_BASE64_RAW\x10\x02\x12\x1c\n" +
	"\x18BYTES_ENCODING_BASE64URL\x10\x03\x12 \n" +
	"\x1cBYTES_ENCODING_BASE64URL_RAW\x10\x04\x12\x16\n" +
	"\x12BYTES_ENCODING_HEX\x10\x05:P\n" +
	"\x06config\x12\x1e.google.protobuf.MethodOptions\x18ӆ\x03 \x01(\v2\x16.sebuf.http.HttpConfigR\x06config:c\n" +
	"\x0eservice_config\x12\x1f.google.protobuf.ServiceOptions\x18Ԇ\x03 \x01(\v2\x19.sebuf.http.ServiceConfigR\rserviceConfig:^\n" +
	"\foneof_config\x12\x1d.google.protobuf.OneofOptions\x18\xe1\x86\x03 \x01(\v2\x17.sebuf.http.OneofConfigR\voneofConfig\x88\x01\x01:a\n" +
	"\x0efield_examples\x12\x1d.google.protobuf.FieldOptions\x18׆\x03 \x01(\v2\x19.sebuf.http.FieldExamplesR\rfieldExamples:N\n" +
	"\x05query\x12\x1d.google.protobuf.FieldOptions\x18؆\x03 \x01(\v2\x17.sebuf.http.QueryConfigR\x05query:7\n" +
	"\x06unwrap\x12\x1d.google.protobuf.FieldOptions\x18ن\x03 \x01(\bR\x06unwrap:d\n" +
	"\x0eint64_encoding\x12\x1d.google.protobuf.FieldOptions\x18چ\x03 \x01(\x0e2\x19.sebuf.http.Int64EncodingR\rint64Encoding\x88\x01\x01:a\n" +
	"\renum_encoding\x12\x1d.google.protobuf.FieldOptions\x18ۆ\x03 \x01(\x0e2\x18.sebuf.http.EnumEncodingR\fenumEncoding\x88\x01\x01:>\n" +
	"\bnullable\x12\x1d.google.protobuf.FieldOptions\x18݆\x03 \x01(\bR\bnullable\x88\x01\x01:d\n" +
	"\x0eempty_behavior\x12\x1d.google.protobuf.FieldOptions\x18ކ\x03 \x01(\x0e2\x19.sebuf.http.EmptyBehaviorR\remptyBehavior\x88\x01\x01:j\n" +
	"\x10timestamp_format\x12\x1d.google.protobuf.FieldOptions\x18߆\x03 \x01(\x0e2\x1b.sebuf.http.TimestampFormatR\x0ftimestampFormat\x88\x01\x01:d\n" +
	"\x0ebytes_encoding\x12\x1d.google.protobuf.FieldOptions\x18\xe0\x86\x03 \x01(\x0e2\x19.sebuf.http.BytesEncodingR\rbytesEncoding\x88\x01\x01:C\n" +
	"\voneof_value\x12\x1d.google.protobuf.FieldOptions\x18\xe2\x86\x03 \x01(\tR\n" +
	"oneofValue\x88\x01\x01:<\n" +
	"\aflatten\x12\x1d.google.protobuf.FieldOptions\x18\xe3\x86\x03 \x01(\bR\aflatten\x88\x01\x01:I\n" +
	"\x0eflatten_prefix\x12\x1d.google.protobuf.FieldOptions\x18\xe4\x86\x03 \x01(\tR\rflattenPrefix\x88\x01\x01:E\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18܆\x03 \x01(\tR\tenumValue\x88\x01\x01B+Z)github.com/SebastienMelki/sebuf/http;httpb\x06proto3"

var (
	file_proto_sebuf_http_annotations_proto_rawDescOnce sync.Once
	file_proto_sebuf_http_annotations_proto_rawDescData []byte
)

func file_proto_sebuf_http_annotations_proto_rawDescGZIP() []byte {
	file_proto_sebuf_http_annotations_proto_rawDescOnce.Do(func() {
		file_proto_sebuf_http_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_annotations_proto_rawDesc), len(file_proto_sebuf_http_annotations_proto_rawDesc)))
	})
	return file_proto_sebuf_http_annotations_proto_rawDescData
}

var file_proto_sebuf_http_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_sebuf_http_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_sebuf_http_annotations_proto_goTypes = []any{
	(HttpMethod)(0),                       // 0: sebuf.http.HttpMethod
	(Int64Encoding)(0),                    // 1: sebuf.http.Int64Encoding
	(EnumEncoding)(0),                     // 2: sebuf.http.EnumEncoding
	(EmptyBehavior)(0),                    // 3: sebuf.http.EmptyBehavior
	(TimestampFormat)(0),                  // 4: sebuf.http.TimestampFormat
	(BytesEncoding)(0),                    // 5: sebuf.http.BytesEncoding
	(*HttpConfig)(nil),                    // 6: sebuf.http.HttpConfig
	(*ServiceConfig)(nil),                 // 7: sebuf.http.ServiceConfig
	(*FieldExamples)(nil),                 // 8: sebuf.http.FieldExamples
	(*QueryConfig)(nil),                   // 9: sebuf.http.QueryConfig
	(*OneofConfig)(nil),                   // 10: sebuf.http.OneofConfig
	(*descriptorpb.MethodOptions)(nil),    // 11: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil),   // 12: google.protobuf.ServiceOptions
	(*descriptorpb.OneofOptions)(nil),     // 13: google.protobuf.OneofOptions
	(*descriptorpb.FieldOptions)(nil),     // 14: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 15: google.protobuf.EnumValueOptions
}
var file_proto_sebuf_http_annotations_proto_depIdxs = []int32{
	0,  // 0: sebuf.http.HttpConfig.method:type_name -> sebuf.http.HttpMethod
	11, // 1: sebuf.http.config:extendee -> google.protobuf.MethodOptions
	12, // 2: sebuf.http.service_config:extendee -> google.protobuf.ServiceOptions
	13, // 3: sebuf.http.oneof_config:extendee -> google.protobuf.OneofOptions
	14, // 4: sebuf.http.field_examples:extendee -> google.protobuf.FieldOptions
	14, // 5: sebuf.http.query:extendee -> google.protobuf.FieldOptions
	14, // 6: sebuf.http.unwrap:extendee -> google.protobuf.FieldOptions
	14, // 7: sebuf.http.int64_encoding:extendee -> google.protobuf.FieldOptions
	14, // 8: sebuf.http.enum_encoding:extendee -> google.protobuf.FieldOptions
	14, // 9: sebuf.http.nullable:extendee -> google.protobuf.FieldOptions
	14, // 10: sebuf.http.empty_behavior:extendee -> google.protobuf.FieldOptions
	14, // 11: sebuf.http.timestamp_format:extendee -> google.protobuf.FieldOptions
	14, // 12: sebuf.http.bytes_encoding:extendee -> google.protobuf.FieldOptions
	14, // 13: sebuf.http.oneof_value:extendee -> google.protobuf.FieldOptions
	14, // 14: sebuf.http.flatten:extendee -> google.protobuf.FieldOptions
	14, // 15: sebuf.http.flatten_prefix:extendee -> google.protobuf.FieldOptions
	15, // 16: sebuf.http.enum_value:extendee -> google.protobuf.EnumValueOptions
	6,  // 17: sebuf.http.config:type_name -> sebuf.http.HttpConfig
	7,  // 18: sebuf.http.service_config:type_name -> sebuf.http.ServiceConfig
	10, // 19: sebuf.http.oneof_config:type_name -> sebuf.http.OneofConfig
	8,  // 20: sebuf.http.field_examples:type_name -> sebuf.http.FieldExamples
	9,  // 21: sebuf.http.query:type_name -> sebuf.http.QueryConfig
	1,  // 22: sebuf.http.int64_encoding:type_name -> sebuf.http.Int64Encoding
	2,  // 23: sebuf.http.enum_encoding:type_name -> sebuf.http.EnumEncoding
	3,  // 24: sebuf.http.empty_behavior:type_name -> sebuf.http.EmptyBehavior
	4,  // 25: sebuf.http.timestamp_format:type_name -> sebuf.http.TimestampFormat
	5,  // 26: sebuf.http.bytes_encoding:type_name -> sebuf.http.BytesEncoding
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	17, // [17:27] is the sub-list for extension type_name
	1,  // [1:17] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sebuf_http_annotations_proto_init() }
func file_proto_sebuf_http_annotations_proto_init() {
	if File_proto_sebuf_http_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_annotations_proto_rawDesc), len(file_proto_sebuf_http_annotations_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   5,
			NumExtensions: 16,
			NumServices:   0,
		},
		GoTypes:           file_proto_sebuf_http_annotations_proto_goTypes,
		DependencyIndexes: file_proto_sebuf_http_annotations_proto_depIdxs,
		EnumInfos:         file_proto_sebuf_http_annotations_proto_enumTypes,
		MessageInfos:      file_proto_sebuf_http_annotations_proto_msgTypes,
		ExtensionInfos:    file_proto_sebuf_http_annotations_proto_extTypes,
	}.Build()
	File_proto_sebuf_http_annotations_proto = out.File
	file_proto_sebuf_http_annotations_proto_goTypes = nil
	file_proto_sebuf_http_annotations_proto_depIdxs = nil
}
