// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/sebuf/http/errors.proto

package http

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidationError is returned when request validation fails.
// It contains a list of field violations describing what went wrong.
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of validation violations
	Violations    []*FieldViolation `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_proto_sebuf_http_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationError) GetViolations() []*FieldViolation {
	if x != nil {
		return x.Violations
	}
	return nil
}

// Error is returned when a handler encounters an error.
// It contains a simple error message that the developer can customize.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message (e.g., "user not found", "database connection failed")
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_sebuf_http_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_errors_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FieldViolation describes a single validation error for a specific field.
type FieldViolation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field path that failed validation (e.g., "user.email" for nested fields)
	// For header validation, this will be the header name (e.g., "X-API-Key")
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Human-readable description of the validation violation
	// (e.g., "must be a valid email address", "required field missing")
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_proto_sebuf_http_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_errors_proto_rawDescGZIP(), []int{2}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_sebuf_http_errors_proto protoreflect.FileDescriptor

const file_proto_sebuf_http_errors_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/sebuf/http/errors.proto\x12\n" +
	"sebuf.http\"M\n" +
	"\x0fValidationError\x12:\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2\x1a.sebuf.http.FieldViolationR\n" +
	"violations\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"H\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescriptionB+Z)github.com/SebastienMelki/sebuf/http;httpb\x06proto3"

var (
	file_proto_sebuf_http_errors_proto_rawDescOnce sync.Once
	file_proto_sebuf_http_errors_proto_rawDescData []byte
)

func file_proto_sebuf_http_errors_proto_rawDescGZIP() []byte {
	file_proto_sebuf_http_errors_proto_rawDescOnce.Do(func() {
		file_proto_sebuf_http_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_errors_proto_rawDesc), len(file_proto_sebuf_http_errors_proto_rawDesc)))
	})
	return file_proto_sebuf_http_errors_proto_rawDescData
}

var file_proto_sebuf_http_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sebuf_http_errors_proto_goTypes = []any{
	(*ValidationError)(nil), // 0: sebuf.http.ValidationError
	(*Error)(nil),           // 1: sebuf.http.Error
	(*FieldViolation)(nil),  // 2: sebuf.http.FieldViolation
}
var file_proto_sebuf_http_errors_proto_depIdxs = []int32{
	2, // 0: sebuf.http.ValidationError.violations:type_name -> sebuf.http.FieldViolation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sebuf_http_errors_proto_init() }
func file_proto_sebuf_http_errors_proto_init() {
	if File_proto_sebuf_http_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_errors_proto_rawDesc), len(file_proto_sebuf_http_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sebuf_http_errors_proto_goTypes,
		DependencyIndexes: file_proto_sebuf_http_errors_proto_depIdxs,
		MessageInfos:      file_proto_sebuf_http_errors_proto_msgTypes,
	}.Build()
	File_proto_sebuf_http_errors_proto = out.File
	file_proto_sebuf_http_errors_proto_goTypes = nil
	file_proto_sebuf_http_errors_proto_depIdxs = nil
}
