// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/sebuf/http/headers.proto

package http

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header definition for OpenAPI specification
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the header parameter
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the header parameter
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Type of the header parameter (string, integer, number, boolean, array)
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Whether the header is required
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// Schema format (e.g. "uuid", "email", "date-time")
	Format string `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	// Example value for the header
	Example string `protobuf:"bytes,6,opt,name=example,proto3" json:"example,omitempty"`
	// Whether the header is deprecated
	Deprecated    bool `protobuf:"varint,7,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_sebuf_http_headers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_headers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_headers_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Header) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Header) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Header) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Header) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *Header) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

// Service-level headers configuration
type ServiceHeaders struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of required headers for all RPCs in the service
	RequiredHeaders []*Header `protobuf:"bytes,1,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceHeaders) Reset() {
	*x = ServiceHeaders{}
	mi := &file_proto_sebuf_http_headers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeaders) ProtoMessage() {}

func (x *ServiceHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_headers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeaders.ProtoReflect.Descriptor instead.
func (*ServiceHeaders) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_headers_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceHeaders) GetRequiredHeaders() []*Header {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

// Method-level headers configuration
type MethodHeaders struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of required headers for this specific RPC
	RequiredHeaders []*Header `protobuf:"bytes,1,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MethodHeaders) Reset() {
	*x = MethodHeaders{}
	mi := &file_proto_sebuf_http_headers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodHeaders) ProtoMessage() {}

func (x *MethodHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_headers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodHeaders.ProtoReflect.Descriptor instead.
func (*MethodHeaders) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_headers_proto_rawDescGZIP(), []int{2}
}

func (x *MethodHeaders) GetRequiredHeaders() []*Header {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

var file_proto_sebuf_http_headers_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceHeaders)(nil),
		Field:         50005,
		Name:          "sebuf.http.service_headers",
		Tag:           "bytes,50005,opt,name=service_headers",
		Filename:      "proto/sebuf/http/headers.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodHeaders)(nil),
		Field:         50006,
		Name:          "sebuf.http.method_headers",
		Tag:           "bytes,50006,opt,name=method_headers",
		Filename:      "proto/sebuf/http/headers.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional sebuf.http.ServiceHeaders service_headers = 50005;
	E_ServiceHeaders = &file_proto_sebuf_http_headers_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional sebuf.http.MethodHeaders method_headers = 50006;
	E_MethodHeaders = &file_proto_sebuf_http_headers_proto_extTypes[1]
)

var File_proto_sebuf_http_headers_proto protoreflect.FileDescriptor

const file_proto_sebuf_http_headers_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/sebuf/http/headers.proto\x12\n" +
	"sebuf.http\x1a google/protobuf/descriptor.proto\"\xc0\x01\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x18\n" +
	"\aexample\x18\x06 \x01(\tR\aexample\x12\x1e\n" +
	"\n" +
	"deprecated\x18\a \x01(\bR\n" +
	"deprecated\"O\n" +
	"\x0eServiceHeaders\x12=\n" +
	"\x10required_headers\x18\x01 \x03(\v2\x12.sebuf.http.HeaderR\x0frequiredHeaders\"N\n" +
	"\rMethodHeaders\x12=\n" +
	"\x10required_headers\x18\x01 \x03(\v2\x12.sebuf.http.HeaderR\x0frequiredHeaders:f\n" +
	"\x0fservice_headers\x12\x1f.google.protobuf.ServiceOptions\x18Ն\x03 \x01(\v2\x1a.sebuf.http.ServiceHeadersR\x0eserviceHeaders:b\n" +
	"\x0emethod_headers\x12\x1e.google.protobuf.MethodOptions\x18ֆ\x03 \x01(\v2\x19.sebuf.http.MethodHeadersR\rmethodHeadersB+Z)github.com/SebastienMelki/sebuf/http;httpb\x06proto3"

var (
	file_proto_sebuf_http_headers_proto_rawDescOnce sync.Once
	file_proto_sebuf_http_headers_proto_rawDescData []byte
)

func file_proto_sebuf_http_headers_proto_rawDescGZIP() []byte {
	file_proto_sebuf_http_headers_proto_rawDescOnce.Do(func() {
		file_proto_sebuf_http_headers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_headers_proto_rawDesc), len(file_proto_sebuf_http_headers_proto_rawDesc)))
	})
	return file_proto_sebuf_http_headers_proto_rawDescData
}

var file_proto_sebuf_http_headers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sebuf_http_headers_proto_goTypes = []any{
	(*Header)(nil),                      // 0: sebuf.http.Header
	(*ServiceHeaders)(nil),              // 1: sebuf.http.ServiceHeaders
	(*MethodHeaders)(nil),               // 2: sebuf.http.MethodHeaders
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 4: google.protobuf.MethodOptions
}
var file_proto_sebuf_http_headers_proto_depIdxs = []int32{
	0, // 0: sebuf.http.ServiceHeaders.required_headers:type_name -> sebuf.http.Header
	0, // 1: sebuf.http.MethodHeaders.required_headers:type_name -> sebuf.http.Header
	3, // 2: sebuf.http.service_headers:extendee -> google.protobuf.ServiceOptions
	4, // 3: sebuf.http.method_headers:extendee -> google.protobuf.MethodOptions
	1, // 4: sebuf.http.service_headers:type_name -> sebuf.http.ServiceHeaders
	2, // 5: sebuf.http.method_headers:type_name -> sebuf.http.MethodHeaders
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_sebuf_http_headers_proto_init() }
func file_proto_sebuf_http_headers_proto_init() {
	if File_proto_sebuf_http_headers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_headers_proto_rawDesc), len(file_proto_sebuf_http_headers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_sebuf_http_headers_proto_goTypes,
		DependencyIndexes: file_proto_sebuf_http_headers_proto_depIdxs,
		MessageInfos:      file_proto_sebuf_http_headers_proto_msgTypes,
		ExtensionInfos:    file_proto_sebuf_http_headers_proto_extTypes,
	}.Build()
	File_proto_sebuf_http_headers_proto = out.File
	file_proto_sebuf_http_headers_proto_goTypes = nil
	file_proto_sebuf_http_headers_proto_depIdxs = nil
}
