/**
 * Bundles the standalone God's Eye View API into one self-contained ESM file.
 *
 * Same idea as docker/build-handlers.mjs: the runtime container installs only
 * docker/runtime-package.json's dependencies, so anything the API needs has
 * to be inlined at build time.
 *
 * The two aliases are the point. `src/gev/vite.config.js` imports `vite` (for
 * `defineConfig` + `loadEnv`) and `vite-plugin-cesium`, neither of which the
 * API server actually needs — it harvests only the `*-proxy` plugins. Without
 * the aliases the bundle would pull Vite, rollup and esbuild into a
 * production image to call two trivial functions.
 *
 * Run: node scripts/build-gev-api.mjs [--outfile <path>]
 */

import { build } from 'esbuild';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { statSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const outIdx = process.argv.indexOf('--outfile');
const outfile = outIdx !== -1 && process.argv[outIdx + 1]
  ? resolve(process.cwd(), process.argv[outIdx + 1])
  : resolve(ROOT, 'dist-gev-api/gev-api-server.mjs');

await build({
  entryPoints: [resolve(ROOT, 'server/gev/serve.mjs')],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  // Keep it readable — this lands in a container where the only debugger is a
  // stack trace, and the file is not shipped to browsers.
  minify: false,
  sourcemap: false,
  alias: {
    vite: resolve(ROOT, 'server/gev/shims/vite.mjs'),
    'vite-plugin-cesium': resolve(ROOT, 'server/gev/shims/vite-plugin-cesium.mjs'),
  },
  // Upstream reads two local GeoJSON packs through `?url` imports and a
  // guarded `node:fs` dynamic import. Neither is on the API server's path,
  // but esbuild still has to resolve them — mark them external so the bundle
  // does not try to inline several megabytes of map data.
  external: ['*.geojsonl?url', '*.geojson?url'],
  banner: {
    // `connect` depends on `debug`, which is CommonJS and calls
    // `require('tty')` lazily. Bundled into ESM that becomes esbuild's
    // "Dynamic require of \"tty\" is not supported" throw at startup.
    // Defining a real `require` satisfies esbuild's own __require fallback,
    // which checks for exactly this before giving up.
    js: '// GENERATED by scripts/build-gev-api.mjs — do not edit.\n'
      + '// Source: server/gev/serve.mjs (+ vendored src/gev/vite.config.js).\n'
      + "import { createRequire as __gevCreateRequire } from 'node:module';\n"
      + 'const require = __gevCreateRequire(import.meta.url);\n',
  },
  logLevel: 'warning',
});

const { size } = statSync(outfile);
console.log(`build-gev-api: ${outfile}`);
console.log(`  ${(size / 1024 / 1024).toFixed(2)} MB`);
