export const config = { runtime: 'edge' };
import { getCorsHeaders, isDisallowedOrigin } from './_cors.js';
import { jsonResponse } from './_json-response.js';

const COUNTRIES = [
  { iso:'US', name:'United States', flag:'🇺🇸', spendingB:858, spendingPct:3.5, personnel:1400000, reserves:800000, nuclear:5500 },
  { iso:'CN', name:'China', flag:'🇨🇳', spendingB:296, spendingPct:1.7, personnel:2035000, reserves:510000, nuclear:410 },
  { iso:'RU', name:'Russia', flag:'🇷🇺', spendingB:109, spendingPct:5.9, personnel:1150000, reserves:2000000, nuclear:6257 },
  { iso:'IN', name:'India', flag:'🇮🇳', spendingB:83.6, spendingPct:2.4, personnel:1455550, reserves:1155000, nuclear:164 },
  { iso:'SA', name:'Saudi Arabia', flag:'🇸🇦', spendingB:75.8, spendingPct:7.4, personnel:257000, reserves:0, nuclear:null },
  { iso:'GB', name:'United Kingdom', flag:'🇬🇧', spendingB:68.5, spendingPct:2.3, personnel:195000, reserves:81000, nuclear:225 },
  { iso:'DE', name:'Germany', flag:'🇩🇪', spendingB:66.8, spendingPct:1.7, personnel:183638, reserves:30000, nuclear:null },
  { iso:'FR', name:'France', flag:'🇫🇷', spendingB:56.6, spendingPct:2.1, personnel:270000, reserves:69000, nuclear:290 },
  { iso:'JP', name:'Japan', flag:'🇯🇵', spendingB:51.4, spendingPct:1.2, personnel:247150, reserves:56000, nuclear:null },
  { iso:'KR', name:'South Korea', flag:'🇰🇷', spendingB:46.4, spendingPct:2.8, personnel:600000, reserves:3100000, nuclear:null },
  { iso:'UA', name:'Ukraine', flag:'🇺🇦', spendingB:44.0, spendingPct:37.1, personnel:900000, reserves:900000, nuclear:null },
  { iso:'AU', name:'Australia', flag:'🇦🇺', spendingB:32.3, spendingPct:2.0, personnel:60000, reserves:28700, nuclear:null },
  { iso:'IL', name:'Israel', flag:'🇮🇱', spendingB:27.5, spendingPct:5.3, personnel:170000, reserves:465000, nuclear:90 },
  { iso:'TR', name:'Turkey', flag:'🇹🇷', spendingB:20.6, spendingPct:2.4, personnel:355000, reserves:379000, nuclear:null },
  { iso:'PK', name:'Pakistan', flag:'🇵🇰', spendingB:10.3, spendingPct:3.6, personnel:654000, reserves:550000, nuclear:170 },
  { iso:'KP', name:'North Korea', flag:'🇰🇵', spendingB:4.0, spendingPct:26.0, personnel:1280000, reserves:600000, nuclear:50 },
  { iso:'IR', name:'Iran', flag:'🇮🇷', spendingB:10.3, spendingPct:2.3, personnel:610000, reserves:350000, nuclear:null },
  { iso:'TW', name:'Taiwan', flag:'🇹🇼', spendingB:16.5, spendingPct:2.5, personnel:163000, reserves:1657000, nuclear:null },
];

const WEAPONS = [
  // === MISSILES ===
  { id:'tomahawk', name:'BGM-109 Tomahawk', category:'missile', subcategory:'Cruise Missile', nations:['US','GB'], status:'active', year:1983, mfr:'Raytheon', desc:'Long-range, all-weather, subsonic cruise missile for land attack.', specs:{'Range':'2,500 km','Speed':'Mach 0.7','Warhead':'450 kg','Guidance':'GPS/TERCOM'}, wiki:'BGM-109_Tomahawk', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Tomahawk_Block_IV_cruise_missile.jpg/320px-Tomahawk_Block_IV_cruise_missile.jpg', wikiUrl:'https://en.wikipedia.org/wiki/BGM-109_Tomahawk' },
  { id:'jassm', name:'AGM-158 JASSM', category:'missile', subcategory:'Stealth Cruise Missile', nations:['US','AU','FI','PL','HU'], status:'active', year:2003, mfr:'Lockheed Martin', desc:'Long-range stealth air-launched cruise missile with low-observable airframe.', specs:{'Range':'370–1,000 km','Warhead':'450 kg','Speed':'Mach 0.8','Guidance':'GPS/IIR'}, wiki:'AGM-158_JASSM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/AGM-158_JASSM.jpg/320px-AGM-158_JASSM.jpg', wikiUrl:'https://en.wikipedia.org/wiki/AGM-158_JASSM' },
  { id:'minuteman3', name:'LGM-30G Minuteman III', category:'missile', subcategory:'ICBM', nations:['US'], status:'active', year:1970, mfr:'Boeing', desc:'Land-based intercontinental ballistic missile; backbone of US nuclear triad.', specs:{'Range':'13,000 km','Warhead':'W87 (300 kt × 3 MIRV)','Speed':'Mach 23','CEP':'200 m'}, wiki:'LGM-30_Minuteman', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Minuteman3launch.jpg/320px-Minuteman3launch.jpg', wikiUrl:'https://en.wikipedia.org/wiki/LGM-30_Minuteman' },
  { id:'arrw', name:'AGM-183A ARRW', category:'missile', subcategory:'Hypersonic Missile', nations:['US'], status:'development', year:2022, mfr:'Lockheed Martin', desc:'Air-launched hypersonic boost-glide weapon for time-critical targets.', specs:{'Range':'>1,600 km','Speed':'Mach 20+','Guidance':'GPS/INS','Launch':'B-52'}, wiki:'AGM-183_ARRW', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/AGM-183_ARRW_separation.jpg/320px-AGM-183_ARRW_separation.jpg', wikiUrl:'https://en.wikipedia.org/wiki/AGM-183_ARRW' },
  { id:'trident2', name:'UGM-133 Trident II D5', category:'missile', subcategory:'SLBM', nations:['US','GB'], status:'active', year:1990, mfr:'Lockheed Martin', desc:'Submarine-launched ballistic missile; sea leg of US/UK nuclear triad.', specs:{'Range':'12,000 km','Warhead':'W88 (475 kt × 8 MIRV)','Speed':'Mach 24','CEP':'90 m'}, wiki:'Trident_(missile)', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Trident_II_missile_image.jpg/320px-Trident_II_missile_image.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Trident_(missile)' },
  { id:'sarmat', name:'RS-28 Sarmat', category:'missile', subcategory:'ICBM', nations:['RU'], status:'active', year:2022, mfr:'Makeyev', desc:'Heavy liquid-fueled ICBM replacing Soviet-era RS-36; capable of polar trajectories.', specs:{'Range':'18,000 km','Warhead':'10–15 MIRV (up to 50 Mt total)','Throw':'10,000 kg','Speed':'Mach 20+'}, wiki:'RS-28_Sarmat', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/RS-28_Sarmat_missile.jpg/320px-RS-28_Sarmat_missile.jpg', wikiUrl:'https://en.wikipedia.org/wiki/RS-28_Sarmat' },
  { id:'iskander', name:'9K720 Iskander-M', category:'missile', subcategory:'Ballistic Missile', nations:['RU'], status:'active', year:2006, mfr:'KBM', desc:'Short-range quasi-ballistic missile with low-flight trajectory to evade ABM systems.', specs:{'Range':'400–500 km','Warhead':'700 kg','Speed':'Mach 6–7','CEP':'5–7 m'}, wiki:'9K720_Iskander', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Iskander-M_MAKS-2011.jpg/320px-Iskander-M_MAKS-2011.jpg', wikiUrl:'https://en.wikipedia.org/wiki/9K720_Iskander' },
  { id:'kinzhal', name:'Kh-47M2 Kinzhal', category:'missile', subcategory:'Hypersonic Missile', nations:['RU'], status:'active', year:2017, mfr:'Raduga', desc:'Air-launched hypersonic aeroballistic missile deployed on MiG-31K and Tu-22M3.', specs:{'Range':'2,000 km','Speed':'Mach 10+','Warhead':'500 kg','Guidance':'INS/GPS'}, wiki:'Kh-47M2_Kinzhal', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Kinzhal_missile.jpg/320px-Kinzhal_missile.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Kh-47M2_Kinzhal' },
  { id:'df41', name:'DF-41 (CSS-X-20)', category:'missile', subcategory:'ICBM', nations:['CN'], status:'active', year:2019, mfr:'CASIC', desc:'Road-mobile/silo ICBM with MIRV capability; longest-range Chinese strategic missile.', specs:{'Range':'12,000–15,000 km','Warhead':'10 MIRV (up to 1 Mt each)','Speed':'Mach 25','CEP':'100–500 m'}, wiki:'DF-41', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/DF-41_2019_parade.jpg/320px-DF-41_2019_parade.jpg', wikiUrl:'https://en.wikipedia.org/wiki/DF-41' },
  { id:'brahmos', name:'BrahMos', category:'missile', subcategory:'Supersonic Cruise Missile', nations:['IN','RU'], status:'active', year:2001, mfr:'BrahMos Aerospace', desc:'World\'s fastest operational cruise missile; joint India-Russia development.', specs:{'Range':'290–800 km','Speed':'Mach 2.8–3.0','Warhead':'200–300 kg','Variants':'Air/Sea/Land/Sub'}, wiki:'BrahMos', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/BrahMos-II_concept.jpg/320px-BrahMos-II_concept.jpg', wikiUrl:'https://en.wikipedia.org/wiki/BrahMos' },
  { id:'shaheen3', name:'Shaheen-III', category:'missile', subcategory:'MRBM', nations:['PK'], status:'active', year:2015, mfr:'NESCOM', desc:'Medium-range nuclear-capable ballistic missile; Pakistan\'s longest-range MRBM.', specs:{'Range':'2,750 km','Payload':'1,000 kg','Guidance':'INS','CEP':'<100 m'}, wiki:'Shaheen-III', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Shaheen_III.jpg/320px-Shaheen_III.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Shaheen-III' },
  { id:'hwasong17', name:'Hwasong-17', category:'missile', subcategory:'ICBM', nations:['KP'], status:'active', year:2022, mfr:'DPRK', desc:'World\'s largest mobile ICBM; North Korea\'s flagship strategic weapon system.', specs:{'Range':'>15,000 km','Warhead':'Multiple RVs (est.)','Speed':'Mach 20+','Basing':'Road-mobile TEL'}, wiki:'Hwasong-17', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Hwasong-17.jpg/320px-Hwasong-17.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Hwasong-17' },
  { id:'fateh110', name:'Fateh-110', category:'missile', subcategory:'Ballistic Missile', nations:['IR'], status:'active', year:2002, mfr:'Iran', desc:'Solid-fuel surface-to-surface missile with GPS guidance; used operationally in 2024.', specs:{'Range':'300 km','Warhead':'650 kg','CEP':'10 m','Speed':'Mach 3'}, wiki:'Fateh-110', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Fateh-110_missile.jpg/320px-Fateh-110_missile.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Fateh-110' },
  // === AIRCRAFT ===
  { id:'f35', name:'F-35 Lightning II', category:'aircraft', subcategory:'Multirole Stealth Fighter', nations:['US','GB','AU','JP','IL','IT','NL','NO','DK','KR','SG','PL','BE','CA'], status:'active', year:2015, mfr:'Lockheed Martin', desc:'5th-generation multirole stealth fighter; largest defense program in history with 3 variants.', specs:{'Max Speed':'Mach 1.6','Range':'2,220 km','Ceiling':'50,000 ft','Weapons':'8,160 kg internal+external'}, wiki:'F-35_Lightning_II', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/F-35A_flight_%282%29.jpg/320px-F-35A_flight_%282%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/F-35_Lightning_II' },
  { id:'f22', name:'F-22 Raptor', category:'aircraft', subcategory:'Air Superiority Fighter', nations:['US'], status:'active', year:2005, mfr:'Lockheed Martin/Boeing', desc:'World\'s first operational 5th-gen fighter; supercruise capability and all-aspect stealth.', specs:{'Max Speed':'Mach 2.25','Range':'2,960 km','Ceiling':'65,000 ft','Thrust':'2×156 kN'}, wiki:'F-22_Raptor', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/F22_Raptor_Edit1_%28cropped%29.jpg/320px-F22_Raptor_Edit1_%28cropped%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/F-22_Raptor' },
  { id:'b21', name:'B-21 Raider', category:'aircraft', subcategory:'Strategic Stealth Bomber', nations:['US'], status:'development', year:2023, mfr:'Northrop Grumman', desc:'Next-generation nuclear-capable stealth bomber; successor to B-2 Spirit.', specs:{'Range':'>9,600 km','Payload':'Classified','Crew':'2','Stealth':'Low-observable all-aspect'}, wiki:'B-21_Raider', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/B-21_Raider_first_flight_%28cropped%29.jpg/320px-B-21_Raider_first_flight_%28cropped%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/B-21_Raider' },
  { id:'b2', name:'B-2 Spirit', category:'aircraft', subcategory:'Strategic Stealth Bomber', nations:['US'], status:'active', year:1997, mfr:'Northrop Grumman', desc:'Flying-wing stealth strategic bomber; capable of nuclear and conventional strike worldwide.', specs:{'Range':'11,100 km','Payload':'23,000 kg','Speed':'Mach 0.95','Weapons':'B61/B83 nuclear, GBU-57'}, wiki:'B-2_Spirit', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/B-2_spirit_bombing.jpg/320px-B-2_spirit_bombing.jpg', wikiUrl:'https://en.wikipedia.org/wiki/B-2_Spirit' },
  { id:'f15ex', name:'F-15EX Eagle II', category:'aircraft', subcategory:'Multirole Fighter', nations:['US'], status:'active', year:2021, mfr:'Boeing', desc:'Advanced variant of F-15; 4th-gen platform with digital backbone and highest payload of any US fighter.', specs:{'Max Speed':'Mach 2.5','Range':'3,900 km','Payload':'13,300 kg','Ceiling':'65,000 ft'}, wiki:'Boeing_F-15EX_Eagle_II', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/F-15EX_first_flight_%28cropped%29.jpg/320px-F-15EX_first_flight_%28cropped%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Boeing_F-15EX_Eagle_II' },
  { id:'su57', name:'Su-57 Felon', category:'aircraft', subcategory:'Stealth Multirole Fighter', nations:['RU'], status:'active', year:2020, mfr:'Sukhoi', desc:'Russia\'s first 5th-gen stealth fighter with supercruise and internal weapons bays.', specs:{'Max Speed':'Mach 2.0','Range':'3,500 km','Ceiling':'66,000 ft','Weapons':'10 hardpoints + 2 internal bays'}, wiki:'Sukhoi_Su-57', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Su-57_Felon_-_2019_MAKS_Airshow_%28cropped%29.jpg/320px-Su-57_Felon_-_2019_MAKS_Airshow_%28cropped%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Sukhoi_Su-57' },
  { id:'tu160', name:'Tu-160 Blackjack', category:'aircraft', subcategory:'Strategic Bomber', nations:['RU'], status:'active', year:1987, mfr:'Tupolev', desc:'World\'s largest and heaviest supersonic combat aircraft; nuclear-capable swing-wing bomber.', specs:{'Max Speed':'Mach 2.05','Range':'12,300 km','Payload':'45,000 kg','Crew':'4'}, wiki:'Tupolev_Tu-160', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Tupolev_Tu-160_%28%22Blackjack%22%29.jpg/320px-Tupolev_Tu-160_%28%22Blackjack%22%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Tupolev_Tu-160' },
  { id:'su35', name:'Su-35S Flanker-E', category:'aircraft', subcategory:'Multirole Fighter', nations:['RU','CN','EG','IR'], status:'active', year:2012, mfr:'Sukhoi', desc:'Highly-maneuverable 4++ gen fighter with thrust-vectoring engines and IRBIS-E radar.', specs:{'Max Speed':'Mach 2.25','Range':'3,600 km','Payload':'8,000 kg','Radar':'IRBIS-E (400 km)'}, wiki:'Sukhoi_Su-35', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Su-35S_in_flight.jpg/320px-Su-35S_in_flight.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Sukhoi_Su-35' },
  { id:'j20', name:'J-20 Mighty Dragon', category:'aircraft', subcategory:'Stealth Multirole Fighter', nations:['CN'], status:'active', year:2017, mfr:'Chengdu Aircraft', desc:'China\'s first operational 5th-gen stealth fighter; emphasizes long-range strike and BVR combat.', specs:{'Max Speed':'Mach 2.0+','Range':'2,700 km','Ceiling':'66,000 ft','Weapons':'6 internal + 4 wing hardpoints'}, wiki:'Chengdu_J-20', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/J-20_at_Airshow_China_2022.jpg/320px-J-20_at_Airshow_China_2022.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Chengdu_J-20' },
  { id:'rafale', name:'Dassault Rafale', category:'aircraft', subcategory:'Multirole Fighter', nations:['FR','EG','IN','QA','GR','HR','AE','ID'], status:'active', year:2001, mfr:'Dassault Aviation', desc:'Omnirole carrier- and land-based fighter; nuclear capable via ASMP-A missile.', specs:{'Max Speed':'Mach 1.8','Range':'3,700 km','Payload':'9,500 kg','Radar':'RBE2 AESA'}, wiki:'Dassault_Rafale', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Rafale_Front_Quarterview.jpg/320px-Rafale_Front_Quarterview.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Dassault_Rafale' },
  { id:'eurofighter', name:'Eurofighter Typhoon', category:'aircraft', subcategory:'Multirole Fighter', nations:['GB','DE','IT','ES','AT','SA','QA','KW','OM','EC'], status:'active', year:2003, mfr:'Eurofighter GmbH', desc:'European 4.5-gen canard-delta swing-role fighter with supercruise capability.', specs:{'Max Speed':'Mach 2.0','Range':'3,790 km','Payload':'9,000 kg','Radar':'Captor-E AESA'}, wiki:'Eurofighter_Typhoon', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Eurofighter_Typhoon_of_the_Royal_Air_Force_%28crop%29.jpg/320px-Eurofighter_Typhoon_of_the_Royal_Air_Force_%28crop%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Eurofighter_Typhoon' },
  { id:'tb2', name:'Bayraktar TB2', category:'drone', subcategory:'Armed UCAV', nations:['TR','UA','AZ','LY','ET','PK','MA','SOM','DJI','MR','UZ','RW','TN','NG','TG','NE','BF'], status:'active', year:2014, mfr:'Baykar', desc:'Turkish armed drone proven in Nagorno-Karabakh, Libya and Ukraine; cheap and effective.', specs:{'Endurance':'27 hr','Range':'300 km','Ceiling':'25,000 ft','Payload':'4× MAM-L/C/Smart'}, wiki:'Bayraktar_TB2', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Bayraktar_TB2_Armed_Unmanned_Aerial_Vehicle.jpg/320px-Bayraktar_TB2_Armed_Unmanned_Aerial_Vehicle.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Bayraktar_TB2' },
  { id:'mq9', name:'MQ-9 Reaper', category:'drone', subcategory:'Armed UCAV', nations:['US','GB','FR','IT','NL','BE','ES','PL'], status:'active', year:2007, mfr:'General Atomics', desc:'Hunter-killer UCAV for persistent ISR and strike; backbone of US drone warfare program.', specs:{'Endurance':'27 hr','Range':'1,850 km','Ceiling':'50,000 ft','Payload':'1,700 kg'}, wiki:'General_Atomics_MQ-9_Reaper', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/MQ-9_Reaper_in_flight_%28edit%29.jpg/320px-MQ-9_Reaper_in_flight_%28edit%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/General_Atomics_MQ-9_Reaper' },
  { id:'su34', name:'Su-34 Fullback', category:'aircraft', subcategory:'Strike Fighter', nations:['RU'], status:'active', year:2006, mfr:'Sukhoi', desc:'Dedicated ground-attack aircraft combining fighter and bomber features with side-by-side seating.', specs:{'Max Speed':'Mach 1.8','Range':'4,000 km','Payload':'8,000 kg','Radar':'Leninets V004'}, wiki:'Sukhoi_Su-34', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Su-34_at_MAKS-2007_%28cropped%29.jpg/320px-Su-34_at_MAKS-2007_%28cropped%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Sukhoi_Su-34' },
  // === NAVAL ===
  { id:'fordcarrier', name:'Gerald R. Ford-class', category:'naval', subcategory:'Aircraft Carrier', nations:['US'], status:'active', year:2017, mfr:'HII Newport News', desc:'World\'s most advanced aircraft carrier; EMALS catapults, 75+ aircraft, nuclear-powered.', specs:{'Displacement':'100,000 t','Length':'337 m','Aircraft':'75+','Reactors':'2× A1B nuclear'}, wiki:'Gerald_R._Ford-class_aircraft_carrier', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/USS_Gerald_R._Ford_%28CVN-78%29_2017.JPG/320px-USS_Gerald_R._Ford_%28CVN-78%29_2017.JPG', wikiUrl:'https://en.wikipedia.org/wiki/Gerald_R._Ford-class_aircraft_carrier' },
  { id:'virginia', name:'Virginia-class Submarine', category:'naval', subcategory:'Attack Submarine (SSN)', nations:['US'], status:'active', year:2004, mfr:'GD/HII', desc:'US Navy\'s primary nuclear-attack submarine; Block V adds Virginia Payload Modules for Tomahawks.', specs:{'Displacement':'10,200 t','Length':'115 m','Speed':'>25 kn','Weapons':'12 VLS + 4 torpedo tubes'}, wiki:'Virginia-class_submarine', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/USS_Virginia_SSN-774.jpg/320px-USS_Virginia_SSN-774.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Virginia-class_submarine' },
  { id:'arleighburke', name:'Arleigh Burke-class Destroyer', category:'naval', subcategory:'Guided Missile Destroyer', nations:['US','JP','KR','AU'], status:'active', year:1991, mfr:'GD Bath Iron Works', desc:'Most numerous destroyer class; Aegis combat system for BMD and area air defense.', specs:{'Displacement':'9,200 t','VLS':'96 cells','Speed':'>30 kn','Weapons':'Tomahawk, SM-3, ESSM'}, wiki:'Arleigh_Burke-class_destroyer', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/USS_Arleigh_Burke_DDG-51.jpg/320px-USS_Arleigh_Burke_DDG-51.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Arleigh_Burke-class_destroyer' },
  { id:'type055', name:'Type 055 (Renhai-class)', category:'naval', subcategory:'Cruiser/Destroyer', nations:['CN'], status:'active', year:2020, mfr:'CSSC/CSIC', desc:'China\'s most powerful surface combatant; 112-cell VLS, dual-band radar, comparable to Ticonderoga.', specs:{'Displacement':'12,000–13,000 t','VLS':'112 cells','Speed':'>30 kn','Length':'180 m'}, wiki:'Type_055_destroyer', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Type_055_destroyer_Nanchang.jpg/320px-Type_055_destroyer_Nanchang.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Type_055_destroyer' },
  { id:'gorshkov', name:'Admiral Gorshkov-class', category:'naval', subcategory:'Frigate', nations:['RU'], status:'active', year:2018, mfr:'Severnaya Verf', desc:'Russia\'s most advanced frigate; Zircon hypersonic missile capable, stealth hull design.', specs:{'Displacement':'5,400 t','VLS':'16 Zircon/Kalibr','Speed':'>29 kn','Radar':'Poliment-Redut'}, wiki:'Admiral_Gorshkov-class_frigate', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Admiral_of_the_Fleet_of_the_Soviet_Union_Gorshkov.jpg/320px-Admiral_of_the_Fleet_of_the_Soviet_Union_Gorshkov.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Admiral_Gorshkov-class_frigate' },
  { id:'yasenm', name:'Yasen-M class (Project 885M)', category:'naval', subcategory:'Nuclear Attack Submarine', nations:['RU'], status:'active', year:2021, mfr:'Sevmash', desc:'Russia\'s most advanced SSN/SSGN; 32 Kalibr/Oniks/Zircon cruise missiles in VLS.', specs:{'Displacement':'13,800 t','Length':'139 m','Speed':'>35 kn submerged','VLS':'32 cells'}, wiki:'Yasen-class_submarine', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/K-561_Kazan%2C_Severodvinsk%2C_2021.jpg/320px-K-561_Kazan%2C_Severodvinsk%2C_2021.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Yasen-class_submarine' },
  { id:'type094', name:'Type 094 (Jin-class)', category:'naval', subcategory:'Nuclear Ballistic Missile Submarine', nations:['CN'], status:'active', year:2007, mfr:'Huludao', desc:'China\'s primary nuclear-armed SSBN; carries JL-2/JL-3 SLBMs for second-strike deterrence.', specs:{'Displacement':'11,000 t','Missiles':'12× JL-2/JL-3','Speed':'>22 kn submerged','Range':'7,400–9,000 km'}, wiki:'Type_094_submarine', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Type094.jpg/320px-Type094.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Type_094_submarine' },
  { id:'astute', name:'Astute-class Submarine', category:'naval', subcategory:'Nuclear Attack Submarine', nations:['GB'], status:'active', year:2010, mfr:'BAE Systems', desc:'UK\'s most capable attack submarine; natural circulation reactor needs no refueling in lifetime.', specs:{'Displacement':'7,800 t','Length':'97 m','Weapons':'Tomahawk + Spearfish','Speed':'>30 kn'}, wiki:'Astute-class_submarine', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/HMS_Astute_S119.jpg/320px-HMS_Astute_S119.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Astute-class_submarine' },
  { id:'insvikrant', name:'INS Vikrant (IAC-1)', category:'naval', subcategory:'Aircraft Carrier', nations:['IN'], status:'active', year:2022, mfr:'Cochin Shipyard', desc:'India\'s first domestically built aircraft carrier; STOBAR configuration with MiG-29K.', specs:{'Displacement':'45,000 t','Length':'262 m','Aircraft':'30+','Speed':'>28 kn'}, wiki:'INS_Vikrant_(2022)', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/INS_Vikrant_%28R11%29_during_sea_trials_2022.jpg/320px-INS_Vikrant_%28R11%29_during_sea_trials_2022.jpg', wikiUrl:'https://en.wikipedia.org/wiki/INS_Vikrant_(2022)' },
  { id:'type45', name:'Type 45 Destroyer (Daring-class)', category:'naval', subcategory:'Air Defence Destroyer', nations:['GB'], status:'active', year:2009, mfr:'BAE Systems', desc:'UK\'s primary air-defence destroyer; SAMPSON radar and Aster 15/30 missiles.', specs:{'Displacement':'7,350 t','VLS':'48 Aster','Speed':'>29 kn','Radar':'SAMPSON'}, wiki:'Type_45_destroyer', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/HMS_Dragon_%28D35%29.jpg/320px-HMS_Dragon_%28D35%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Type_45_destroyer' },
  // === ARMORED ===
  { id:'m1a2', name:'M1A2 SEPv3 Abrams', category:'armored', subcategory:'Main Battle Tank', nations:['US','SA','EG','AU','PL','TW','KW','MA','GR','IQ','UA'], status:'active', year:1980, mfr:'General Dynamics', desc:'US main battle tank; 3rd-gen composite armor, 120mm smoothbore, depleted uranium armor package.', specs:{'Weight':'73.6 t','Gun':'M256 120mm','Speed':'67 km/h','Crew':'4'}, wiki:'M1_Abrams', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/M1A1_Abrams_in_formation.jpg/320px-M1A1_Abrams_in_formation.jpg', wikiUrl:'https://en.wikipedia.org/wiki/M1_Abrams' },
  { id:'t14', name:'T-14 Armata', category:'armored', subcategory:'Main Battle Tank', nations:['RU'], status:'development', year:2022, mfr:'Uralvagonzavod', desc:'Russia\'s next-gen unmanned-turret MBT; active protection system, separated crew capsule.', specs:{'Weight':'55 t','Gun':'2A82-1M 125mm (autoloaded)','Speed':'80 km/h','APS':'Afganit'}, wiki:'T-14_Armata', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/2018_Moscow_Victory_Day_Parade_%28Cropped%29.jpg/320px-2018_Moscow_Victory_Day_Parade_%28Cropped%29.jpg', wikiUrl:'https://en.wikipedia.org/wiki/T-14_Armata' },
  { id:'type99a', name:'Type 99A (ZTZ-99A)', category:'armored', subcategory:'Main Battle Tank', nations:['CN'], status:'active', year:2011, mfr:'Norinco', desc:'China\'s most advanced MBT; explosive reactive armor, active protection, 125mm autoloaded gun.', specs:{'Weight':'58 t','Gun':'ZPT-98 125mm','Speed':'80 km/h','Range':'600 km'}, wiki:'Type_99_tank', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Type99A2-2015parade.jpg/320px-Type99A2-2015parade.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Type_99_tank' },
  { id:'leopard2a7', name:'Leopard 2A7+', category:'armored', subcategory:'Main Battle Tank', nations:['DE','NO','SE','FI','NL','DK','PL','HU','CZ','CH','GR','TK','CA','AU','QA','SA','UA'], status:'active', year:2014, mfr:'KMW', desc:'Germany\'s premier MBT; widely exported, combat-proven, urban-warfare package with reinforced floor.', specs:{'Weight':'67.5 t','Gun':'Rh-120 L/55','Speed':'72 km/h','Crew':'4'}, wiki:'Leopard_2', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Leopard_2_A7_in_Kiel.jpg/320px-Leopard_2_A7_in_Kiel.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Leopard_2' },
  { id:'merkava4', name:'Merkava Mk 4', category:'armored', subcategory:'Main Battle Tank', nations:['IL'], status:'active', year:2004, mfr:'IMI/Elbit', desc:'Israeli MBT designed for crew survivability; Trophy APS, rear troop compartment, 120mm gun.', specs:{'Weight':'65 t','Gun':'MG253 120mm','APS':'Trophy','Crew':'4 + 6 passengers'}, wiki:'Merkava', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Merkava-IV-Batash-latrun-1.jpg/320px-Merkava-IV-Batash-latrun-1.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Merkava' },
  { id:'k2', name:'K2 Black Panther', category:'armored', subcategory:'Main Battle Tank', nations:['KR','PL','NO'], status:'active', year:2014, mfr:'Hyundai Rotem', desc:'South Korea\'s 3rd-gen MBT; hydro-pneumatic suspension, 120mm gun with autoloader, hunter-killer.', specs:{'Weight':'55 t','Gun':'CN08 120mm','Speed':'70 km/h','APS':'KAPS'}, wiki:'K2_Black_Panther', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/K2_Black_Panther_at_Seoul_ADEX_2015.jpg/320px-K2_Black_Panther_at_Seoul_ADEX_2015.jpg', wikiUrl:'https://en.wikipedia.org/wiki/K2_Black_Panther' },
  // === AIR DEFENSE ===
  { id:'s400', name:'S-400 Triumf', category:'air-defense', subcategory:'Long-Range SAM System', nations:['RU','CN','IN','TR'], status:'active', year:2007, mfr:'Almaz-Antey', desc:'Russia\'s premier long-range SAM; can engage aircraft, drones, cruise and ballistic missiles.', specs:{'Range':'400 km (40N6)','Altitude':'30 km','Targets':'80 simultaneous','Radar':'91N6E'}, wiki:'S-400_missile_system', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/S-400_Triumph_battery.jpg/320px-S-400_Triumph_battery.jpg', wikiUrl:'https://en.wikipedia.org/wiki/S-400_missile_system' },
  { id:'irondom', name:'Iron Dome', category:'air-defense', subcategory:'Short-Range Air Defense', nations:['IL','US'], status:'active', year:2011, mfr:'Rafael/IAI', desc:'Israel\'s rocket/artillery/mortar intercept system; uses Tamir interceptors with proximity fuze.', specs:{'Range':'4–70 km','Altitude':'10 km','Intercept Rate':'>90%','Battery':'3–4 launchers + radar'}, wiki:'Iron_Dome', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Iron_Dome_night_intercept2.jpg/320px-Iron_Dome_night_intercept2.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Iron_Dome' },
  { id:'patriot', name:'MIM-104 Patriot PAC-3', category:'air-defense', subcategory:'Medium-Range SAM', nations:['US','DE','NL','JP','SA','KW','TW','GR','IL','KR','QA','UA','PL','RO','SE'], status:'active', year:1984, mfr:'Raytheon', desc:'US/NATO primary area air defense system; PAC-3 MSE variant defeats ballistic missiles via hit-to-kill.', specs:{'Range':'100 km','Altitude':'24 km','Intercept':'Aircraft + TBM + cruise','Radar':'AN/MPQ-65'}, wiki:'MIM-104_Patriot', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Patriot_System_2.jpg/320px-Patriot_System_2.jpg', wikiUrl:'https://en.wikipedia.org/wiki/MIM-104_Patriot' },
  { id:'thaad', name:'THAAD', category:'air-defense', subcategory:'Terminal High Altitude Area Defense', nations:['US','SA','AE','KR'], status:'active', year:2008, mfr:'Lockheed Martin', desc:'Hit-to-kill ballistic missile defense for theater protection; can intercept inside and above atmosphere.', specs:{'Range':'200 km','Altitude':'150 km','Speed':'Mach 8+ (interceptor)','Radar':'AN/TPY-2'}, wiki:'Terminal_High_Altitude_Area_Defense', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/THAAD_launch.jpg/320px-THAAD_launch.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Terminal_High_Altitude_Area_Defense' },
  { id:'s500', name:'S-500 Prometheus', category:'air-defense', subcategory:'Anti-Ballistic Missile System', nations:['RU'], status:'active', year:2021, mfr:'Almaz-Antey', desc:'Russia\'s next-gen strategic ABM system; can intercept hypersonic glide vehicles and satellites.', specs:{'Range':'600 km','Altitude':'200 km','Targets':'Hypersonic + ICBM warheads','Speed':'Mach 5+ interceptor'}, wiki:'S-500_missile_system', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/S-500_missile_system.jpg/320px-S-500_missile_system.jpg', wikiUrl:'https://en.wikipedia.org/wiki/S-500_missile_system' },
  { id:'arrow3', name:'Arrow 3', category:'air-defense', subcategory:'Exo-Atmospheric ABM', nations:['IL','DE'], status:'active', year:2017, mfr:'IAI/Boeing', desc:'Upper-tier Israeli ABM system; intercepts ballistic missiles in space (exo-atmospheric).', specs:{'Range':'2,400 km','Altitude':'100+ km','Speed':'Mach 9','Guidance':'Electro-optical seeker'}, wiki:'Arrow_3', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Arrow_3.jpg/320px-Arrow_3.jpg', wikiUrl:'https://en.wikipedia.org/wiki/Arrow_3' },
  { id:'hq9', name:'HQ-9 (Hong Qi-9)', category:'air-defense', subcategory:'Long-Range SAM', nations:['CN','TR'], status:'active', year:1997, mfr:'CASIC', desc:'China\'s primary long-range SAM; inspired by S-300, exported to Turkey (controversial NATO issue).', specs:{'Range':'200 km','Altitude':'30 km','Guidance':'Active radar homing','Radar':'HT-233'}, wiki:'HQ-9', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/HQ-9_2015_parade.jpg/320px-HQ-9_2015_parade.jpg', wikiUrl:'https://en.wikipedia.org/wiki/HQ-9' },
  // === NUCLEAR DELIVERY ===
  { id:'b61', name:'B61-12 Nuclear Bomb', category:'nuclear', subcategory:'Tactical Nuclear Weapon', nations:['US','NATO'], status:'active', year:2022, mfr:'Sandia/TA-55', desc:'US precision-guided nuclear gravity bomb; upgrades four B61 variants into single tail-kit guided bomb.', specs:{'Yield':'0.3–50 kt (dial-a-yield)','CEP':'30 m','Delivery':'F-15E/F-35/Tornado/F-16','Length':'3.58 m'}, wiki:'B61_nuclear_bomb', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/B61_bomb.jpg/320px-B61_bomb.jpg', wikiUrl:'https://en.wikipedia.org/wiki/B61_nuclear_bomb' },
  { id:'df5b', name:'DF-5B (CSS-4)', category:'nuclear', subcategory:'Silo-Based ICBM', nations:['CN'], status:'active', year:1981, mfr:'CASIC', desc:'China\'s oldest ICBM still in service; liquid-fueled silo-based with MIRV capability in DF-5B variant.', specs:{'Range':'13,000 km','Warhead':'4–5 MIRV','Yield':'4–5 Mt each','Status':'Silo-based'}, wiki:'DF-5', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/DF-5_ICBM.jpg/320px-DF-5_ICBM.jpg', wikiUrl:'https://en.wikipedia.org/wiki/DF-5' },
];

export default async function handler(req) {
  const corsHeaders = getCorsHeaders(req, 'GET, OPTIONS');
  if (isDisallowedOrigin(req)) return jsonResponse({ error: 'Forbidden' }, 403, corsHeaders);
  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== 'GET') return jsonResponse({ error: 'Method not allowed' }, 405, corsHeaders);
  return jsonResponse(
    { weapons: WEAPONS, countries: COUNTRIES, fetchedAt: new Date().toISOString() },
    200,
    { ...corsHeaders, 'Cache-Control': 'public, max-age=3600' }
  );
}
